"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


APIKeyStatus = Literal[
    "API_KEY_STATUS_UNSPECIFIED",
    "API_KEY_STATUS_ACTIVE",
    "API_KEY_STATUS_DISABLED",
    "API_KEY_STATUS_REVOKED",
]
