"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tracefilter import TraceFilter, TraceFilterTypedDict
from datetime import datetime
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FindLogPatternsRequestTypedDict(TypedDict):
    from_: datetime
    to: datetime
    query: NotRequired[str]
    filter_operator: NotRequired[str]
    filters: NotRequired[List[TraceFilterTypedDict]]
    limit: NotRequired[int]
    r"""Maximum patterns to return. Defaults to 50."""


class FindLogPatternsRequest(BaseModel):
    from_: Annotated[datetime, pydantic.Field(alias="from")]

    to: datetime

    query: Optional[str] = None

    filter_operator: Optional[str] = None

    filters: Optional[List[TraceFilter]] = None

    limit: Optional[int] = None
    r"""Maximum patterns to return. Defaults to 50."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["query", "filter_operator", "filters", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FindLogPatternsRequest.model_rebuild()
except NameError:
    pass
