"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


LegacyTokenFamily = Literal[
    "LEGACY_TOKEN_FAMILY_UNSPECIFIED",
    "LEGACY_TOKEN_FAMILY_ROUTER_JWT",
    "LEGACY_TOKEN_FAMILY_PROJECT_JWT",
    "LEGACY_TOKEN_FAMILY_WORKSPACE_JWT",
]
