"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .audiocontentpartschema import (
    AudioContentPartSchema,
    AudioContentPartSchemaTypedDict,
)
from .filecontentpartschema import FileContentPartSchema, FileContentPartSchemaTypedDict
from .imagecontentpartschema import (
    ImageContentPartSchema,
    ImageContentPartSchemaTypedDict,
)
from .reasoningpartschema import ReasoningPartSchema, ReasoningPartSchemaTypedDict
from .redactedreasoningpartschema import (
    RedactedReasoningPartSchema,
    RedactedReasoningPartSchemaTypedDict,
)
from .refusalpartschema import RefusalPartSchema, RefusalPartSchemaTypedDict
from .textcontentpartschema import TextContentPartSchema, TextContentPartSchemaTypedDict
from .thinkingconfigdisabledschema import (
    ThinkingConfigDisabledSchema,
    ThinkingConfigDisabledSchemaTypedDict,
)
from .thinkingconfigenabledschema import (
    ThinkingConfigEnabledSchema,
    ThinkingConfigEnabledSchemaTypedDict,
)
from orq_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from orq_ai_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    get_discriminator,
)
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import (
    Annotated,
    NotRequired,
    TypeAliasType,
    TypedDict,
    deprecated,
)


class ListPromptVersionsRequestTypedDict(TypedDict):
    prompt_id: str
    limit: NotRequired[int]
    r"""A limit on the number of objects to be returned. Limit can range between 1 and 50, and the default is 10"""
    starting_after: NotRequired[str]
    r"""A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 20 objects, ending with `01JJ1HDHN79XAS7A01WB3HYSDB`, your subsequent call can include `after=01JJ1HDHN79XAS7A01WB3HYSDB` in order to fetch the next page of the list."""
    ending_before: NotRequired[str]
    r"""A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 20 objects, starting with `01JJ1HDHN79XAS7A01WB3HYSDB`, your subsequent call can include `before=01JJ1HDHN79XAS7A01WB3HYSDB` in order to fetch the previous page of the list."""


class ListPromptVersionsRequest(BaseModel):
    prompt_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""A limit on the number of objects to be returned. Limit can range between 1 and 50, and the default is 10"""

    starting_after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 20 objects, ending with `01JJ1HDHN79XAS7A01WB3HYSDB`, your subsequent call can include `after=01JJ1HDHN79XAS7A01WB3HYSDB` in order to fetch the next page of the list."""

    ending_before: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 20 objects, starting with `01JJ1HDHN79XAS7A01WB3HYSDB`, your subsequent call can include `before=01JJ1HDHN79XAS7A01WB3HYSDB` in order to fetch the previous page of the list."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "starting_after", "ending_before"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsObject = Literal["list",]


ListPromptVersionsModelType = Literal[
    "chat",
    "completion",
    "embedding",
    "image",
    "tts",
    "stt",
    "rerank",
    "ocr",
    "moderation",
    "vision",
]
r"""The modality of the model"""


ListPromptVersionsFormat = Literal[
    "url",
    "b64_json",
    "text",
    "json_object",
]
r"""Only supported on `image` models."""


ListPromptVersionsResponseFormat6 = Literal[
    "json",
    "text",
    "srt",
    "verbose_json",
    "vtt",
]


ListPromptVersionsResponseFormat5 = Literal[
    "url",
    "base64_json",
]


ListPromptVersionsResponseFormat4 = Literal[
    "mp3",
    "opus",
    "aac",
    "flac",
    "wav",
    "pcm",
]


ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONResponseBodyType = (
    Literal["text",]
)


class ListPromptVersionsResponseFormat3TypedDict(TypedDict):
    type: ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONResponseBodyType


class ListPromptVersionsResponseFormat3(BaseModel):
    type: ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONResponseBodyType


ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONType = Literal[
    "json_object",
]


class ListPromptVersionsResponseFormat2TypedDict(TypedDict):
    type: ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONType


class ListPromptVersionsResponseFormat2(BaseModel):
    type: ListPromptVersionsResponseFormatPromptsResponse200ApplicationJSONType


ListPromptVersionsResponseFormatPromptsResponse200Type = Literal["json_schema",]


class ListPromptVersionsResponseFormatPromptsResponseJSONSchemaTypedDict(TypedDict):
    name: str
    schema_: Dict[str, Any]
    description: NotRequired[str]
    strict: NotRequired[bool]


class ListPromptVersionsResponseFormatPromptsResponseJSONSchema(BaseModel):
    name: str

    schema_: Annotated[Dict[str, Any], pydantic.Field(alias="schema")]

    description: Optional[str] = None

    strict: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "strict"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsResponseFormat1TypedDict(TypedDict):
    type: ListPromptVersionsResponseFormatPromptsResponse200Type
    json_schema: ListPromptVersionsResponseFormatPromptsResponseJSONSchemaTypedDict
    display_name: NotRequired[str]


class ListPromptVersionsResponseFormat1(BaseModel):
    type: ListPromptVersionsResponseFormatPromptsResponse200Type

    json_schema: ListPromptVersionsResponseFormatPromptsResponseJSONSchema

    display_name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsPromptsResponseFormatTypedDict = TypeAliasType(
    "ListPromptVersionsPromptsResponseFormatTypedDict",
    Union[
        ListPromptVersionsResponseFormat2TypedDict,
        ListPromptVersionsResponseFormat3TypedDict,
        ListPromptVersionsResponseFormat1TypedDict,
        ListPromptVersionsResponseFormat4,
        ListPromptVersionsResponseFormat5,
        ListPromptVersionsResponseFormat6,
    ],
)
r"""An object specifying the format that the model must output.

Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema

Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which ensures the message the model generates is valid JSON.

Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \"stuck\" request. Also note that the message content may be partially cut off if finish_reason=\"length\", which indicates the generation exceeded max_tokens or the conversation exceeded the max context length.
"""


ListPromptVersionsPromptsResponseFormat = TypeAliasType(
    "ListPromptVersionsPromptsResponseFormat",
    Union[
        ListPromptVersionsResponseFormat2,
        ListPromptVersionsResponseFormat3,
        ListPromptVersionsResponseFormat1,
        ListPromptVersionsResponseFormat4,
        ListPromptVersionsResponseFormat5,
        ListPromptVersionsResponseFormat6,
    ],
)
r"""An object specifying the format that the model must output.

Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema

Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which ensures the message the model generates is valid JSON.

Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \"stuck\" request. Also note that the message content may be partially cut off if finish_reason=\"length\", which indicates the generation exceeded max_tokens or the conversation exceeded the max context length.
"""


ListPromptVersionsPhotoRealVersion = Literal[
    "v1",
    "v2",
]
r"""The version of photoReal to use. Must be v1 or v2. Only available for `leonardoai` provider"""


ListPromptVersionsEncodingFormat = Literal[
    "float",
    "base64",
]
r"""The format to return the embeddings"""


ListPromptVersionsPromptsReasoningEffort = Literal[
    "none",
    "disable",
    "minimal",
    "low",
    "medium",
    "high",
]
r"""Constrains effort on reasoning for reasoning models. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response."""


ListPromptVersionsVerbosity = Literal[
    "low",
    "medium",
    "high",
]
r"""Controls the verbosity of the model output."""


ListPromptVersionsThinkingLevel = Literal[
    "low",
    "high",
]
r"""The level of thinking to use for the model. Only supported by `Google AI`"""


class ListPromptVersionsModelParametersTypedDict(TypedDict):
    r"""Model Parameters: Not all parameters apply to every model"""

    temperature: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    max_tokens: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    top_k: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    top_p: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    frequency_penalty: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    presence_penalty: NotRequired[float]
    r"""Only supported on `chat` and `completion` models."""
    num_images: NotRequired[float]
    r"""Only supported on `image` models."""
    seed: NotRequired[float]
    r"""Best effort deterministic seed for the model. Currently only OpenAI models support these"""
    format_: NotRequired[ListPromptVersionsFormat]
    r"""Only supported on `image` models."""
    dimensions: NotRequired[str]
    r"""Only supported on `image` models."""
    quality: NotRequired[str]
    r"""Only supported on `image` models."""
    style: NotRequired[str]
    r"""Only supported on `image` models."""
    response_format: NotRequired[
        Nullable[ListPromptVersionsPromptsResponseFormatTypedDict]
    ]
    r"""An object specifying the format that the model must output.

    Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema

    Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which ensures the message the model generates is valid JSON.

    Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \"stuck\" request. Also note that the message content may be partially cut off if finish_reason=\"length\", which indicates the generation exceeded max_tokens or the conversation exceeded the max context length.
    """
    photo_real_version: NotRequired[ListPromptVersionsPhotoRealVersion]
    r"""The version of photoReal to use. Must be v1 or v2. Only available for `leonardoai` provider"""
    encoding_format: NotRequired[ListPromptVersionsEncodingFormat]
    r"""The format to return the embeddings"""
    reasoning_effort: NotRequired[ListPromptVersionsPromptsReasoningEffort]
    r"""Constrains effort on reasoning for reasoning models. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response."""
    budget_tokens: NotRequired[float]
    r"""Gives the model enhanced reasoning capabilities for complex tasks. A value of 0 disables thinking. The minimum budget tokens for thinking are 1024. The Budget Tokens should never exceed the Max Tokens parameter. Only supported by `Anthropic`"""
    verbosity: NotRequired[ListPromptVersionsVerbosity]
    r"""Controls the verbosity of the model output."""
    thinking_level: NotRequired[ListPromptVersionsThinkingLevel]
    r"""The level of thinking to use for the model. Only supported by `Google AI`"""


class ListPromptVersionsModelParameters(BaseModel):
    r"""Model Parameters: Not all parameters apply to every model"""

    temperature: Optional[float] = None
    r"""Only supported on `chat` and `completion` models."""

    max_tokens: Annotated[Optional[float], pydantic.Field(alias="maxTokens")] = None
    r"""Only supported on `chat` and `completion` models."""

    top_k: Annotated[Optional[float], pydantic.Field(alias="topK")] = None
    r"""Only supported on `chat` and `completion` models."""

    top_p: Annotated[Optional[float], pydantic.Field(alias="topP")] = None
    r"""Only supported on `chat` and `completion` models."""

    frequency_penalty: Annotated[
        Optional[float], pydantic.Field(alias="frequencyPenalty")
    ] = None
    r"""Only supported on `chat` and `completion` models."""

    presence_penalty: Annotated[
        Optional[float], pydantic.Field(alias="presencePenalty")
    ] = None
    r"""Only supported on `chat` and `completion` models."""

    num_images: Annotated[Optional[float], pydantic.Field(alias="numImages")] = None
    r"""Only supported on `image` models."""

    seed: Optional[float] = None
    r"""Best effort deterministic seed for the model. Currently only OpenAI models support these"""

    format_: Annotated[
        Optional[ListPromptVersionsFormat], pydantic.Field(alias="format")
    ] = None
    r"""Only supported on `image` models."""

    dimensions: Optional[str] = None
    r"""Only supported on `image` models."""

    quality: Optional[str] = None
    r"""Only supported on `image` models."""

    style: Optional[str] = None
    r"""Only supported on `image` models."""

    response_format: Annotated[
        OptionalNullable[ListPromptVersionsPromptsResponseFormat],
        pydantic.Field(alias="responseFormat"),
    ] = UNSET
    r"""An object specifying the format that the model must output.

    Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema

    Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which ensures the message the model generates is valid JSON.

    Important: when using JSON mode, you must also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \"stuck\" request. Also note that the message content may be partially cut off if finish_reason=\"length\", which indicates the generation exceeded max_tokens or the conversation exceeded the max context length.
    """

    photo_real_version: Annotated[
        Optional[ListPromptVersionsPhotoRealVersion],
        pydantic.Field(alias="photoRealVersion"),
    ] = None
    r"""The version of photoReal to use. Must be v1 or v2. Only available for `leonardoai` provider"""

    encoding_format: Optional[ListPromptVersionsEncodingFormat] = None
    r"""The format to return the embeddings"""

    reasoning_effort: Annotated[
        Optional[ListPromptVersionsPromptsReasoningEffort],
        pydantic.Field(alias="reasoningEffort"),
    ] = None
    r"""Constrains effort on reasoning for reasoning models. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response."""

    budget_tokens: Annotated[Optional[float], pydantic.Field(alias="budgetTokens")] = (
        None
    )
    r"""Gives the model enhanced reasoning capabilities for complex tasks. A value of 0 disables thinking. The minimum budget tokens for thinking are 1024. The Budget Tokens should never exceed the Max Tokens parameter. Only supported by `Anthropic`"""

    verbosity: Optional[ListPromptVersionsVerbosity] = None
    r"""Controls the verbosity of the model output."""

    thinking_level: Annotated[
        Optional[ListPromptVersionsThinkingLevel], pydantic.Field(alias="thinkingLevel")
    ] = None
    r"""The level of thinking to use for the model. Only supported by `Google AI`"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "temperature",
                "maxTokens",
                "topK",
                "topP",
                "frequencyPenalty",
                "presencePenalty",
                "numImages",
                "seed",
                "format",
                "dimensions",
                "quality",
                "style",
                "responseFormat",
                "photoRealVersion",
                "encoding_format",
                "reasoningEffort",
                "budgetTokens",
                "verbosity",
                "thinkingLevel",
            ]
        )
        nullable_fields = set(["responseFormat"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListPromptVersionsProvider = Literal[
    "openai",
    "groq",
    "cohere",
    "azure",
    "aws",
    "google",
    "google-ai",
    "huggingface",
    "togetherai",
    "perplexity",
    "anthropic",
    "leonardoai",
    "fal",
    "nvidia",
    "jina",
    "elevenlabs",
    "litellm",
    "cerebras",
    "openailike",
    "bytedance",
    "mistral",
    "deepseek",
    "contextualai",
    "moonshotai",
    "zai",
    "minimax",
    "slack",
]


ListPromptVersionsRole = Literal[
    "system",
    "assistant",
    "user",
    "exception",
    "tool",
    "prompt",
    "correction",
    "expected_output",
]
r"""The role of the prompt message"""


ListPromptVersions2PromptsResponseType = Literal["file",]
r"""The type of the content part. Always `file`."""


class ListPromptVersions2FileTypedDict(TypedDict):
    file_data: NotRequired[str]
    r"""The file data as a data URI string in the format 'data:<mime-type>;base64,<base64-encoded-data>'. Example: 'data:image/png;base64,iVBORw0KGgoAAAANS...'"""
    uri: NotRequired[str]
    r"""URL to the file. Only supported by Anthropic Claude models for PDF files."""
    mime_type: NotRequired[str]
    r"""MIME type of the file (e.g., application/pdf, image/png)"""
    filename: NotRequired[str]
    r"""The name of the file, used when passing the file to the model as a string."""


class ListPromptVersions2File(BaseModel):
    file_data: Optional[str] = None
    r"""The file data as a data URI string in the format 'data:<mime-type>;base64,<base64-encoded-data>'. Example: 'data:image/png;base64,iVBORw0KGgoAAAANS...'"""

    uri: Optional[str] = None
    r"""URL to the file. Only supported by Anthropic Claude models for PDF files."""

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None
    r"""MIME type of the file (e.g., application/pdf, image/png)"""

    filename: Optional[str] = None
    r"""The name of the file, used when passing the file to the model as a string."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_data", "uri", "mimeType", "filename"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersions23TypedDict(TypedDict):
    type: ListPromptVersions2PromptsResponseType
    r"""The type of the content part. Always `file`."""
    file: ListPromptVersions2FileTypedDict


class ListPromptVersions23(BaseModel):
    type: ListPromptVersions2PromptsResponseType
    r"""The type of the content part. Always `file`."""

    file: ListPromptVersions2File


ListPromptVersions2PromptsType = Literal["image_url",]


class ListPromptVersions2ImageURLTypedDict(TypedDict):
    url: str
    r"""Either a URL of the image or the base64 encoded data URI."""
    id: NotRequired[str]
    r"""The orq.ai id of the image"""
    detail: NotRequired[str]
    r"""Specifies the detail level of the image. Currently only supported with OpenAI models"""


class ListPromptVersions2ImageURL(BaseModel):
    url: str
    r"""Either a URL of the image or the base64 encoded data URI."""

    id: Optional[str] = None
    r"""The orq.ai id of the image"""

    detail: Optional[str] = None
    r"""Specifies the detail level of the image. Currently only supported with OpenAI models"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "detail"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersions22TypedDict(TypedDict):
    r"""The image part of the prompt message. Only supported with vision models."""

    type: ListPromptVersions2PromptsType
    image_url: ListPromptVersions2ImageURLTypedDict


class ListPromptVersions22(BaseModel):
    r"""The image part of the prompt message. Only supported with vision models."""

    type: ListPromptVersions2PromptsType

    image_url: ListPromptVersions2ImageURL


ListPromptVersions2Type = Literal["text",]


class ListPromptVersions21TypedDict(TypedDict):
    r"""Text content part of a prompt message"""

    type: ListPromptVersions2Type
    text: str


class ListPromptVersions21(BaseModel):
    r"""Text content part of a prompt message"""

    type: ListPromptVersions2Type

    text: str


ListPromptVersionsContent2TypedDict = TypeAliasType(
    "ListPromptVersionsContent2TypedDict",
    Union[
        ListPromptVersions21TypedDict,
        ListPromptVersions22TypedDict,
        ListPromptVersions23TypedDict,
    ],
)


ListPromptVersionsContent2 = Annotated[
    Union[
        Annotated[ListPromptVersions21, Tag("text")],
        Annotated[ListPromptVersions22, Tag("image_url")],
        Annotated[ListPromptVersions23, Tag("file")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


ListPromptVersionsContentTypedDict = TypeAliasType(
    "ListPromptVersionsContentTypedDict",
    Union[str, List[ListPromptVersionsContent2TypedDict]],
)
r"""The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts. Can be null for tool messages in certain scenarios."""


ListPromptVersionsContent = TypeAliasType(
    "ListPromptVersionsContent", Union[str, List[ListPromptVersionsContent2]]
)
r"""The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts. Can be null for tool messages in certain scenarios."""


ListPromptVersionsPromptsType = Literal["function",]


class ListPromptVersionsFunctionTypedDict(TypedDict):
    name: str
    arguments: str
    r"""JSON string arguments for the functions"""


class ListPromptVersionsFunction(BaseModel):
    name: str

    arguments: str
    r"""JSON string arguments for the functions"""


class ListPromptVersionsToolCallsTypedDict(TypedDict):
    type: ListPromptVersionsPromptsType
    function: ListPromptVersionsFunctionTypedDict
    id: NotRequired[str]
    index: NotRequired[float]


class ListPromptVersionsToolCalls(BaseModel):
    type: ListPromptVersionsPromptsType

    function: ListPromptVersionsFunction

    id: Optional[str] = None

    index: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "index"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsMessagesTypedDict(TypedDict):
    role: ListPromptVersionsRole
    r"""The role of the prompt message"""
    content: Nullable[ListPromptVersionsContentTypedDict]
    r"""The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts. Can be null for tool messages in certain scenarios."""
    tool_calls: NotRequired[List[ListPromptVersionsToolCallsTypedDict]]
    tool_call_id: NotRequired[Nullable[str]]


class ListPromptVersionsMessages(BaseModel):
    role: ListPromptVersionsRole
    r"""The role of the prompt message"""

    content: Nullable[ListPromptVersionsContent]
    r"""The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts. Can be null for tool messages in certain scenarios."""

    tool_calls: Optional[List[ListPromptVersionsToolCalls]] = None

    tool_call_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tool_calls", "tool_call_id"])
        nullable_fields = set(["content", "tool_call_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


@deprecated(
    "warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
)
class ListPromptVersionsPromptConfigTypedDict(TypedDict):
    r"""[DEPRECATED] Use the `prompt` property instead. A list of messages compatible with the openAI schema."""

    messages: List[ListPromptVersionsMessagesTypedDict]
    stream: NotRequired[bool]
    model: NotRequired[Nullable[str]]
    model_db_id: NotRequired[Nullable[str]]
    r"""The id of the resource"""
    model_type: NotRequired[Nullable[ListPromptVersionsModelType]]
    r"""The modality of the model"""
    model_parameters: NotRequired[ListPromptVersionsModelParametersTypedDict]
    r"""Model Parameters: Not all parameters apply to every model"""
    provider: NotRequired[Nullable[ListPromptVersionsProvider]]
    integration_id: NotRequired[Nullable[str]]
    r"""The ID of the integration to use"""
    version: NotRequired[str]


@deprecated(
    "warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
)
class ListPromptVersionsPromptConfig(BaseModel):
    r"""[DEPRECATED] Use the `prompt` property instead. A list of messages compatible with the openAI schema."""

    messages: List[ListPromptVersionsMessages]

    stream: Optional[bool] = None

    model: OptionalNullable[str] = UNSET

    model_db_id: OptionalNullable[str] = UNSET
    r"""The id of the resource"""

    model_type: OptionalNullable[ListPromptVersionsModelType] = UNSET
    r"""The modality of the model"""

    model_parameters: Optional[ListPromptVersionsModelParameters] = None
    r"""Model Parameters: Not all parameters apply to every model"""

    provider: OptionalNullable[ListPromptVersionsProvider] = UNSET

    integration_id: OptionalNullable[str] = UNSET
    r"""The ID of the integration to use"""

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "stream",
                "model",
                "model_db_id",
                "model_type",
                "model_parameters",
                "provider",
                "integration_id",
                "version",
            ]
        )
        nullable_fields = set(
            ["model", "model_db_id", "model_type", "provider", "integration_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListPromptVersionsVoice = Literal[
    "alloy",
    "echo",
    "fable",
    "onyx",
    "nova",
    "shimmer",
]
r"""The voice the model uses to respond. Supported voices are alloy, echo, fable, onyx, nova, and shimmer."""


ListPromptVersionsPromptsFormat = Literal[
    "wav",
    "mp3",
    "flac",
    "opus",
    "pcm16",
]
r"""Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16."""


class ListPromptVersionsAudioTypedDict(TypedDict):
    r"""Parameters for audio output. Required when audio output is requested with modalities: [\"audio\"]. Learn more."""

    voice: ListPromptVersionsVoice
    r"""The voice the model uses to respond. Supported voices are alloy, echo, fable, onyx, nova, and shimmer."""
    format_: ListPromptVersionsPromptsFormat
    r"""Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16."""


class ListPromptVersionsAudio(BaseModel):
    r"""Parameters for audio output. Required when audio output is requested with modalities: [\"audio\"]. Learn more."""

    voice: ListPromptVersionsVoice
    r"""The voice the model uses to respond. Supported voices are alloy, echo, fable, onyx, nova, and shimmer."""

    format_: Annotated[ListPromptVersionsPromptsFormat, pydantic.Field(alias="format")]
    r"""Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16."""


ListPromptVersionsResponseFormatPromptsResponseType = Literal["json_schema",]


class ListPromptVersionsResponseFormatJSONSchemaTypedDict(TypedDict):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    description: NotRequired[str]
    r"""A description of what the response format is for, used by the model to determine how to respond in the format."""
    schema_: NotRequired[Any]
    r"""The schema for the response format, described as a JSON Schema object."""
    strict: NotRequired[bool]
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the schema field. Only a subset of JSON Schema is supported when strict is true."""


class ListPromptVersionsResponseFormatJSONSchema(BaseModel):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""

    description: Optional[str] = None
    r"""A description of what the response format is for, used by the model to determine how to respond in the format."""

    schema_: Annotated[Optional[Any], pydantic.Field(alias="schema")] = None
    r"""The schema for the response format, described as a JSON Schema object."""

    strict: Optional[bool] = False
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the schema field. Only a subset of JSON Schema is supported when strict is true."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "schema", "strict"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsResponseFormatPromptsJSONSchemaTypedDict(TypedDict):
    r"""

    JSON Schema response format. Used to generate structured JSON responses
    """

    type: ListPromptVersionsResponseFormatPromptsResponseType
    json_schema: ListPromptVersionsResponseFormatJSONSchemaTypedDict


class ListPromptVersionsResponseFormatPromptsJSONSchema(BaseModel):
    r"""

    JSON Schema response format. Used to generate structured JSON responses
    """

    type: ListPromptVersionsResponseFormatPromptsResponseType

    json_schema: ListPromptVersionsResponseFormatJSONSchema


ListPromptVersionsResponseFormatPromptsType = Literal["json_object",]


class ListPromptVersionsResponseFormatJSONObjectTypedDict(TypedDict):
    r"""

    JSON object response format. An older method of generating JSON responses. Using `json_schema` is recommended for models that support it. Note that the model will not generate JSON without a system or user message instructing it to do so.
    """

    type: ListPromptVersionsResponseFormatPromptsType


class ListPromptVersionsResponseFormatJSONObject(BaseModel):
    r"""

    JSON object response format. An older method of generating JSON responses. Using `json_schema` is recommended for models that support it. Note that the model will not generate JSON without a system or user message instructing it to do so.
    """

    type: ListPromptVersionsResponseFormatPromptsType


ListPromptVersionsResponseFormatType = Literal["text",]


class ListPromptVersionsResponseFormatTextTypedDict(TypedDict):
    r"""

    Default response format. Used to generate text responses
    """

    type: ListPromptVersionsResponseFormatType


class ListPromptVersionsResponseFormatText(BaseModel):
    r"""

    Default response format. Used to generate text responses
    """

    type: ListPromptVersionsResponseFormatType


ListPromptVersionsResponseFormatTypedDict = TypeAliasType(
    "ListPromptVersionsResponseFormatTypedDict",
    Union[
        ListPromptVersionsResponseFormatTextTypedDict,
        ListPromptVersionsResponseFormatJSONObjectTypedDict,
        ListPromptVersionsResponseFormatPromptsJSONSchemaTypedDict,
    ],
)
r"""An object specifying the format that the model must output"""


ListPromptVersionsResponseFormat = Annotated[
    Union[
        Annotated[ListPromptVersionsResponseFormatText, Tag("text")],
        Annotated[ListPromptVersionsResponseFormatJSONObject, Tag("json_object")],
        Annotated[
            ListPromptVersionsResponseFormatPromptsJSONSchema, Tag("json_schema")
        ],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""An object specifying the format that the model must output"""


ListPromptVersionsReasoningEffort = Literal[
    "none",
    "minimal",
    "low",
    "medium",
    "high",
    "xhigh",
]
r"""Constrains effort on reasoning for [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.

- `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool calls are supported for all reasoning values in gpt-5.1.
- All models before `gpt-5.1` default to `medium` reasoning effort, and do not support `none`.
- The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
- `xhigh` is currently only supported for `gpt-5.1-codex-max`.

Any of \"none\", \"minimal\", \"low\", \"medium\", \"high\", \"xhigh\".
"""


ListPromptVersionsStopTypedDict = TypeAliasType(
    "ListPromptVersionsStopTypedDict", Union[str, List[str]]
)
r"""Up to 4 sequences where the API will stop generating further tokens."""


ListPromptVersionsStop = TypeAliasType("ListPromptVersionsStop", Union[str, List[str]])
r"""Up to 4 sequences where the API will stop generating further tokens."""


class ListPromptVersionsStreamOptionsTypedDict(TypedDict):
    r"""Options for streaming response. Only set this when you set stream: true."""

    include_usage: NotRequired[bool]
    r"""If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value."""


class ListPromptVersionsStreamOptions(BaseModel):
    r"""Options for streaming response. Only set this when you set stream: true."""

    include_usage: Optional[bool] = None
    r"""If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["include_usage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsThinkingTypedDict = TypeAliasType(
    "ListPromptVersionsThinkingTypedDict",
    Union[ThinkingConfigDisabledSchemaTypedDict, ThinkingConfigEnabledSchemaTypedDict],
)


ListPromptVersionsThinking = Annotated[
    Union[
        Annotated[ThinkingConfigDisabledSchema, Tag("disabled")],
        Annotated[ThinkingConfigEnabledSchema, Tag("enabled")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


ListPromptVersionsToolChoiceType = Literal["function",]
r"""The type of the tool. Currently, only function is supported."""


class ListPromptVersionsToolChoiceFunctionTypedDict(TypedDict):
    name: str
    r"""The name of the function to call."""


class ListPromptVersionsToolChoiceFunction(BaseModel):
    name: str
    r"""The name of the function to call."""


class ListPromptVersionsToolChoice2TypedDict(TypedDict):
    function: ListPromptVersionsToolChoiceFunctionTypedDict
    type: NotRequired[ListPromptVersionsToolChoiceType]
    r"""The type of the tool. Currently, only function is supported."""


class ListPromptVersionsToolChoice2(BaseModel):
    function: ListPromptVersionsToolChoiceFunction

    type: Optional[ListPromptVersionsToolChoiceType] = None
    r"""The type of the tool. Currently, only function is supported."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsToolChoice1 = Literal[
    "none",
    "auto",
    "required",
]


ListPromptVersionsToolChoiceTypedDict = TypeAliasType(
    "ListPromptVersionsToolChoiceTypedDict",
    Union[ListPromptVersionsToolChoice2TypedDict, ListPromptVersionsToolChoice1],
)
r"""Controls which (if any) tool is called by the model."""


ListPromptVersionsToolChoice = TypeAliasType(
    "ListPromptVersionsToolChoice",
    Union[ListPromptVersionsToolChoice2, ListPromptVersionsToolChoice1],
)
r"""Controls which (if any) tool is called by the model."""


ListPromptVersionsModalities = Literal[
    "text",
    "audio",
]


ListPromptVersionsID1 = Literal[
    "orq_pii_detection",
    "orq_sexual_moderation",
    "orq_harmful_moderation",
]
r"""The key of the guardrail."""


ListPromptVersionsIDTypedDict = TypeAliasType(
    "ListPromptVersionsIDTypedDict", Union[ListPromptVersionsID1, str]
)


ListPromptVersionsID = TypeAliasType(
    "ListPromptVersionsID", Union[ListPromptVersionsID1, str]
)


ListPromptVersionsExecuteOn = Literal[
    "input",
    "output",
]
r"""Determines whether the guardrail runs on the input (user message) or output (model response)."""


class ListPromptVersionsGuardrailsTypedDict(TypedDict):
    id: ListPromptVersionsIDTypedDict
    execute_on: ListPromptVersionsExecuteOn
    r"""Determines whether the guardrail runs on the input (user message) or output (model response)."""


class ListPromptVersionsGuardrails(BaseModel):
    id: ListPromptVersionsID

    execute_on: ListPromptVersionsExecuteOn
    r"""Determines whether the guardrail runs on the input (user message) or output (model response)."""


class ListPromptVersionsFallbacksTypedDict(TypedDict):
    model: str
    r"""Fallback model identifier"""


class ListPromptVersionsFallbacks(BaseModel):
    model: str
    r"""Fallback model identifier"""


class ListPromptVersionsRetryTypedDict(TypedDict):
    r"""Retry configuration for the request"""

    count: NotRequired[float]
    r"""Number of retry attempts (1-5)"""
    on_codes: NotRequired[List[float]]
    r"""HTTP status codes that trigger retry logic"""


class ListPromptVersionsRetry(BaseModel):
    r"""Retry configuration for the request"""

    count: Optional[float] = 3
    r"""Number of retry attempts (1-5)"""

    on_codes: Optional[List[float]] = None
    r"""HTTP status codes that trigger retry logic"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "on_codes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsType = Literal["exact_match",]


class ListPromptVersionsCacheTypedDict(TypedDict):
    r"""Cache configuration for the request."""

    type: ListPromptVersionsType
    ttl: NotRequired[float]
    r"""Time to live for cached responses in seconds. Maximum 259200 seconds (3 days)."""


class ListPromptVersionsCache(BaseModel):
    r"""Cache configuration for the request."""

    type: ListPromptVersionsType

    ttl: Optional[float] = 1800
    r"""Time to live for cached responses in seconds. Maximum 259200 seconds (3 days)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ttl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsLoadBalancerType = Literal["weight_based",]


class ListPromptVersionsLoadBalancerModelsTypedDict(TypedDict):
    model: str
    r"""Model identifier for load balancing"""
    weight: NotRequired[float]
    r"""Weight assigned to this model for load balancing"""


class ListPromptVersionsLoadBalancerModels(BaseModel):
    model: str
    r"""Model identifier for load balancing"""

    weight: Optional[float] = 0.5
    r"""Weight assigned to this model for load balancing"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["weight"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsLoadBalancer1TypedDict(TypedDict):
    type: ListPromptVersionsLoadBalancerType
    models: List[ListPromptVersionsLoadBalancerModelsTypedDict]


class ListPromptVersionsLoadBalancer1(BaseModel):
    type: ListPromptVersionsLoadBalancerType

    models: List[ListPromptVersionsLoadBalancerModels]


ListPromptVersionsLoadBalancerTypedDict = ListPromptVersionsLoadBalancer1TypedDict
r"""Load balancer configuration for the request."""


ListPromptVersionsLoadBalancer = ListPromptVersionsLoadBalancer1
r"""Load balancer configuration for the request."""


class ListPromptVersionsTimeoutTypedDict(TypedDict):
    r"""Timeout configuration to apply to the request. If the request exceeds the timeout, it will be retried or fallback to the next model if configured."""

    call_timeout: float
    r"""Timeout value in milliseconds"""


class ListPromptVersionsTimeout(BaseModel):
    r"""Timeout configuration to apply to the request. If the request exceeds the timeout, it will be retried or fallback to the next model if configured."""

    call_timeout: float
    r"""Timeout value in milliseconds"""


ListPromptVersionsMessagesPromptsResponse200Role = Literal["tool",]
r"""The role of the messages author, in this case tool."""


ListPromptVersionsContentPromptsResponse2002TypedDict = TextContentPartSchemaTypedDict


ListPromptVersionsContentPromptsResponse2002 = TextContentPartSchema


ListPromptVersionsMessagesPromptsResponse200ContentTypedDict = TypeAliasType(
    "ListPromptVersionsMessagesPromptsResponse200ContentTypedDict",
    Union[str, List[ListPromptVersionsContentPromptsResponse2002TypedDict]],
)
r"""The contents of the tool message."""


ListPromptVersionsMessagesPromptsResponse200Content = TypeAliasType(
    "ListPromptVersionsMessagesPromptsResponse200Content",
    Union[str, List[ListPromptVersionsContentPromptsResponse2002]],
)
r"""The contents of the tool message."""


ListPromptVersionsMessagesPromptsType = Literal["ephemeral",]
r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""


ListPromptVersionsMessagesTTL = Literal[
    "5m",
    "1h",
]
r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

- `5m`: 5 minutes
- `1h`: 1 hour

Defaults to `5m`. Only supported by `Anthropic` Claude models.
"""


class ListPromptVersionsMessagesCacheControlTypedDict(TypedDict):
    type: ListPromptVersionsMessagesPromptsType
    r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""
    ttl: NotRequired[ListPromptVersionsMessagesTTL]
    r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

    - `5m`: 5 minutes
    - `1h`: 1 hour

    Defaults to `5m`. Only supported by `Anthropic` Claude models.
    """


class ListPromptVersionsMessagesCacheControl(BaseModel):
    type: ListPromptVersionsMessagesPromptsType
    r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""

    ttl: Optional[ListPromptVersionsMessagesTTL] = "5m"
    r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

    - `5m`: 5 minutes
    - `1h`: 1 hour

    Defaults to `5m`. Only supported by `Anthropic` Claude models.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ttl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsMessagesToolMessageTypedDict(TypedDict):
    role: ListPromptVersionsMessagesPromptsResponse200Role
    r"""The role of the messages author, in this case tool."""
    content: ListPromptVersionsMessagesPromptsResponse200ContentTypedDict
    r"""The contents of the tool message."""
    tool_call_id: Nullable[str]
    r"""Tool call that this message is responding to."""
    cache_control: NotRequired[ListPromptVersionsMessagesCacheControlTypedDict]


class ListPromptVersionsMessagesToolMessage(BaseModel):
    role: ListPromptVersionsMessagesPromptsResponse200Role
    r"""The role of the messages author, in this case tool."""

    content: ListPromptVersionsMessagesPromptsResponse200Content
    r"""The contents of the tool message."""

    tool_call_id: Nullable[str]
    r"""Tool call that this message is responding to."""

    cache_control: Optional[ListPromptVersionsMessagesCacheControl] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cache_control"])
        nullable_fields = set(["tool_call_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListPromptVersionsContentPromptsResponse2TypedDict = TypeAliasType(
    "ListPromptVersionsContentPromptsResponse2TypedDict",
    Union[
        RefusalPartSchemaTypedDict,
        RedactedReasoningPartSchemaTypedDict,
        TextContentPartSchemaTypedDict,
        ReasoningPartSchemaTypedDict,
    ],
)


ListPromptVersionsContentPromptsResponse2 = Annotated[
    Union[
        Annotated[TextContentPartSchema, Tag("text")],
        Annotated[RefusalPartSchema, Tag("refusal")],
        Annotated[ReasoningPartSchema, Tag("reasoning")],
        Annotated[RedactedReasoningPartSchema, Tag("redacted_reasoning")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


ListPromptVersionsMessagesPromptsResponseContentTypedDict = TypeAliasType(
    "ListPromptVersionsMessagesPromptsResponseContentTypedDict",
    Union[str, List[ListPromptVersionsContentPromptsResponse2TypedDict]],
)
r"""The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified."""


ListPromptVersionsMessagesPromptsResponseContent = TypeAliasType(
    "ListPromptVersionsMessagesPromptsResponseContent",
    Union[str, List[ListPromptVersionsContentPromptsResponse2]],
)
r"""The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified."""


ListPromptVersionsMessagesPromptsResponseRole = Literal["assistant",]
r"""The role of the messages author, in this case `assistant`."""


class ListPromptVersionsMessagesAudioTypedDict(TypedDict):
    r"""Data about a previous audio response from the model."""

    id: str
    r"""Unique identifier for a previous audio response from the model."""


class ListPromptVersionsMessagesAudio(BaseModel):
    r"""Data about a previous audio response from the model."""

    id: str
    r"""Unique identifier for a previous audio response from the model."""


ListPromptVersionsMessagesType = Literal["function",]
r"""The type of the tool. Currently, only `function` is supported."""


class ListPromptVersionsMessagesFunctionTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the function to call."""
    arguments: NotRequired[str]
    r"""The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function."""


class ListPromptVersionsMessagesFunction(BaseModel):
    name: Optional[str] = None
    r"""The name of the function to call."""

    arguments: Optional[str] = None
    r"""The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "arguments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsMessagesToolCallsTypedDict(TypedDict):
    id: str
    r"""The ID of the tool call."""
    type: ListPromptVersionsMessagesType
    r"""The type of the tool. Currently, only `function` is supported."""
    function: ListPromptVersionsMessagesFunctionTypedDict
    thought_signature: NotRequired[str]
    r"""Encrypted representation of the model internal reasoning state during function calling. Required by Gemini 3 models when continuing a conversation after a tool call."""


class ListPromptVersionsMessagesToolCalls(BaseModel):
    id: str
    r"""The ID of the tool call."""

    type: ListPromptVersionsMessagesType
    r"""The type of the tool. Currently, only `function` is supported."""

    function: ListPromptVersionsMessagesFunction

    thought_signature: Optional[str] = None
    r"""Encrypted representation of the model internal reasoning state during function calling. Required by Gemini 3 models when continuing a conversation after a tool call."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["thought_signature"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersionsMessagesAssistantMessageTypedDict(TypedDict):
    role: ListPromptVersionsMessagesPromptsResponseRole
    r"""The role of the messages author, in this case `assistant`."""
    content: NotRequired[
        Nullable[ListPromptVersionsMessagesPromptsResponseContentTypedDict]
    ]
    r"""The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified."""
    refusal: NotRequired[Nullable[str]]
    r"""The refusal message by the assistant."""
    name: NotRequired[str]
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""
    audio: NotRequired[Nullable[ListPromptVersionsMessagesAudioTypedDict]]
    r"""Data about a previous audio response from the model."""
    tool_calls: NotRequired[List[ListPromptVersionsMessagesToolCallsTypedDict]]
    r"""The tool calls generated by the model, such as function calls."""


class ListPromptVersionsMessagesAssistantMessage(BaseModel):
    role: ListPromptVersionsMessagesPromptsResponseRole
    r"""The role of the messages author, in this case `assistant`."""

    content: OptionalNullable[ListPromptVersionsMessagesPromptsResponseContent] = UNSET
    r"""The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified."""

    refusal: OptionalNullable[str] = UNSET
    r"""The refusal message by the assistant."""

    name: Optional[str] = None
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    audio: OptionalNullable[ListPromptVersionsMessagesAudio] = UNSET
    r"""Data about a previous audio response from the model."""

    tool_calls: Optional[List[ListPromptVersionsMessagesToolCalls]] = None
    r"""The tool calls generated by the model, such as function calls."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["content", "refusal", "name", "audio", "tool_calls"])
        nullable_fields = set(["content", "refusal", "audio"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListPromptVersionsMessagesPromptsRole = Literal["user",]
r"""The role of the messages author, in this case `user`."""


ListPromptVersions2PromptsResponse200Type = Literal["file",]
r"""The type of the content part. Always `file`."""


ListPromptVersions2PromptsResponse200ApplicationJSONType = Literal["ephemeral",]
r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""


ListPromptVersions2TTL = Literal[
    "5m",
    "1h",
]
r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

- `5m`: 5 minutes
- `1h`: 1 hour

Defaults to `5m`. Only supported by `Anthropic` Claude models.
"""


class ListPromptVersions2CacheControlTypedDict(TypedDict):
    type: ListPromptVersions2PromptsResponse200ApplicationJSONType
    r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""
    ttl: NotRequired[ListPromptVersions2TTL]
    r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

    - `5m`: 5 minutes
    - `1h`: 1 hour

    Defaults to `5m`. Only supported by `Anthropic` Claude models.
    """


class ListPromptVersions2CacheControl(BaseModel):
    type: ListPromptVersions2PromptsResponse200ApplicationJSONType
    r"""Create a cache control breakpoint at this content block. Accepts only the value \"ephemeral\"."""

    ttl: Optional[ListPromptVersions2TTL] = "5m"
    r"""The time-to-live for the cache control breakpoint. This may be one of the following values:

    - `5m`: 5 minutes
    - `1h`: 1 hour

    Defaults to `5m`. Only supported by `Anthropic` Claude models.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ttl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListPromptVersions24TypedDict(TypedDict):
    type: ListPromptVersions2PromptsResponse200Type
    r"""The type of the content part. Always `file`."""
    file: FileContentPartSchemaTypedDict
    r"""File data for the content part. Must contain either file_data or uri, but not both."""
    cache_control: NotRequired[ListPromptVersions2CacheControlTypedDict]


class ListPromptVersions24(BaseModel):
    type: ListPromptVersions2PromptsResponse200Type
    r"""The type of the content part. Always `file`."""

    file: FileContentPartSchema
    r"""File data for the content part. Must contain either file_data or uri, but not both."""

    cache_control: Optional[ListPromptVersions2CacheControl] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cache_control"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsContentPrompts2TypedDict = TypeAliasType(
    "ListPromptVersionsContentPrompts2TypedDict",
    Union[
        AudioContentPartSchemaTypedDict,
        TextContentPartSchemaTypedDict,
        ImageContentPartSchemaTypedDict,
        ListPromptVersions24TypedDict,
    ],
)


ListPromptVersionsContentPrompts2 = Annotated[
    Union[
        Annotated[TextContentPartSchema, Tag("text")],
        Annotated[ImageContentPartSchema, Tag("image_url")],
        Annotated[AudioContentPartSchema, Tag("input_audio")],
        Annotated[ListPromptVersions24, Tag("file")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


ListPromptVersionsMessagesPromptsContentTypedDict = TypeAliasType(
    "ListPromptVersionsMessagesPromptsContentTypedDict",
    Union[str, List[ListPromptVersionsContentPrompts2TypedDict]],
)
r"""The contents of the user message."""


ListPromptVersionsMessagesPromptsContent = TypeAliasType(
    "ListPromptVersionsMessagesPromptsContent",
    Union[str, List[ListPromptVersionsContentPrompts2]],
)
r"""The contents of the user message."""


class ListPromptVersionsMessagesUserMessageTypedDict(TypedDict):
    role: ListPromptVersionsMessagesPromptsRole
    r"""The role of the messages author, in this case `user`."""
    content: ListPromptVersionsMessagesPromptsContentTypedDict
    r"""The contents of the user message."""
    name: NotRequired[str]
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""


class ListPromptVersionsMessagesUserMessage(BaseModel):
    role: ListPromptVersionsMessagesPromptsRole
    r"""The role of the messages author, in this case `user`."""

    content: ListPromptVersionsMessagesPromptsContent
    r"""The contents of the user message."""

    name: Optional[str] = None
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsMessagesRole = Literal["system",]
r"""The role of the messages author, in this case `system`."""


ListPromptVersionsMessagesContentTypedDict = TypeAliasType(
    "ListPromptVersionsMessagesContentTypedDict",
    Union[str, List[TextContentPartSchemaTypedDict]],
)
r"""The contents of the system message."""


ListPromptVersionsMessagesContent = TypeAliasType(
    "ListPromptVersionsMessagesContent", Union[str, List[TextContentPartSchema]]
)
r"""The contents of the system message."""


class ListPromptVersionsMessagesSystemMessageTypedDict(TypedDict):
    r"""Developer-provided instructions that the model should follow, regardless of messages sent by the user."""

    role: ListPromptVersionsMessagesRole
    r"""The role of the messages author, in this case `system`."""
    content: ListPromptVersionsMessagesContentTypedDict
    r"""The contents of the system message."""
    name: NotRequired[str]
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""


class ListPromptVersionsMessagesSystemMessage(BaseModel):
    r"""Developer-provided instructions that the model should follow, regardless of messages sent by the user."""

    role: ListPromptVersionsMessagesRole
    r"""The role of the messages author, in this case `system`."""

    content: ListPromptVersionsMessagesContent
    r"""The contents of the system message."""

    name: Optional[str] = None
    r"""An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPromptVersionsPromptsMessagesTypedDict = TypeAliasType(
    "ListPromptVersionsPromptsMessagesTypedDict",
    Union[
        ListPromptVersionsMessagesSystemMessageTypedDict,
        ListPromptVersionsMessagesUserMessageTypedDict,
        ListPromptVersionsMessagesToolMessageTypedDict,
        ListPromptVersionsMessagesAssistantMessageTypedDict,
    ],
)


ListPromptVersionsPromptsMessages = Annotated[
    Union[
        Annotated[ListPromptVersionsMessagesSystemMessage, Tag("system")],
        Annotated[ListPromptVersionsMessagesUserMessage, Tag("user")],
        Annotated[ListPromptVersionsMessagesAssistantMessage, Tag("assistant")],
        Annotated[ListPromptVersionsMessagesToolMessage, Tag("tool")],
    ],
    Discriminator(lambda m: get_discriminator(m, "role", "role")),
]


class ListPromptVersionsPromptFieldTypedDict(TypedDict):
    r"""Prompt configuration with model and messages. Use this instead of prompt_config."""

    name: NotRequired[str]
    r"""The name to display on the trace. If not specified, the default system name will be used."""
    audio: NotRequired[Nullable[ListPromptVersionsAudioTypedDict]]
    r"""Parameters for audio output. Required when audio output is requested with modalities: [\"audio\"]. Learn more."""
    frequency_penalty: NotRequired[Nullable[float]]
    r"""Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim."""
    max_tokens: NotRequired[Nullable[int]]
    r"""`[Deprecated]`. The maximum number of tokens that can be generated in the chat completion. This value can be used to control costs for text generated via API.

    This value is now `deprecated` in favor of `max_completion_tokens`, and is not compatible with o1 series models.
    """
    max_completion_tokens: NotRequired[Nullable[int]]
    r"""An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens"""
    logprobs: NotRequired[Nullable[bool]]
    r"""Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message."""
    top_logprobs: NotRequired[Nullable[int]]
    r"""An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used."""
    n: NotRequired[Nullable[int]]
    r"""How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs."""
    presence_penalty: NotRequired[Nullable[float]]
    r"""Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics."""
    response_format: NotRequired[ListPromptVersionsResponseFormatTypedDict]
    r"""An object specifying the format that the model must output"""
    reasoning_effort: NotRequired[ListPromptVersionsReasoningEffort]
    r"""Constrains effort on reasoning for [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.

    - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool calls are supported for all reasoning values in gpt-5.1.
    - All models before `gpt-5.1` default to `medium` reasoning effort, and do not support `none`.
    - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
    - `xhigh` is currently only supported for `gpt-5.1-codex-max`.

    Any of \"none\", \"minimal\", \"low\", \"medium\", \"high\", \"xhigh\".
    """
    verbosity: NotRequired[str]
    r"""Adjusts response verbosity. Lower levels yield shorter answers."""
    seed: NotRequired[Nullable[float]]
    r"""If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result."""
    stop: NotRequired[Nullable[ListPromptVersionsStopTypedDict]]
    r"""Up to 4 sequences where the API will stop generating further tokens."""
    stream_options: NotRequired[Nullable[ListPromptVersionsStreamOptionsTypedDict]]
    r"""Options for streaming response. Only set this when you set stream: true."""
    thinking: NotRequired[ListPromptVersionsThinkingTypedDict]
    temperature: NotRequired[Nullable[float]]
    r"""What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic."""
    top_p: NotRequired[Nullable[float]]
    r"""An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass."""
    top_k: NotRequired[Nullable[float]]
    r"""Limits the model to consider only the top k most likely tokens at each step."""
    tool_choice: NotRequired[ListPromptVersionsToolChoiceTypedDict]
    r"""Controls which (if any) tool is called by the model."""
    parallel_tool_calls: NotRequired[bool]
    r"""Whether to enable parallel function calling during tool use."""
    modalities: NotRequired[Nullable[List[ListPromptVersionsModalities]]]
    r"""Output types that you would like the model to generate. Most models are capable of generating text, which is the default: [\"text\"]. The gpt-4o-audio-preview model can also be used to generate audio. To request that this model generate both text and audio responses, you can use: [\"text\", \"audio\"]."""
    guardrails: NotRequired[List[ListPromptVersionsGuardrailsTypedDict]]
    r"""A list of guardrails to apply to the request."""
    fallbacks: NotRequired[List[ListPromptVersionsFallbacksTypedDict]]
    r"""Array of fallback models to use if primary model fails"""
    retry: NotRequired[ListPromptVersionsRetryTypedDict]
    r"""Retry configuration for the request"""
    cache: NotRequired[ListPromptVersionsCacheTypedDict]
    r"""Cache configuration for the request."""
    load_balancer: NotRequired[ListPromptVersionsLoadBalancerTypedDict]
    r"""Load balancer configuration for the request."""
    timeout: NotRequired[ListPromptVersionsTimeoutTypedDict]
    r"""Timeout configuration to apply to the request. If the request exceeds the timeout, it will be retried or fallback to the next model if configured."""
    messages: NotRequired[List[ListPromptVersionsPromptsMessagesTypedDict]]
    r"""Array of messages that make up the conversation. Each message has a role (system, user, assistant, or tool) and content."""
    model: NotRequired[Nullable[str]]
    r"""Model ID used to generate the response, like `openai/gpt-4o` or `anthropic/claude-3-5-sonnet-20241022`. For private models, use format: `{workspaceKey}@{provider}/{model}`."""
    version: NotRequired[str]


class ListPromptVersionsPromptField(BaseModel):
    r"""Prompt configuration with model and messages. Use this instead of prompt_config."""

    name: Optional[str] = None
    r"""The name to display on the trace. If not specified, the default system name will be used."""

    audio: OptionalNullable[ListPromptVersionsAudio] = UNSET
    r"""Parameters for audio output. Required when audio output is requested with modalities: [\"audio\"]. Learn more."""

    frequency_penalty: OptionalNullable[float] = UNSET
    r"""Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim."""

    max_tokens: OptionalNullable[int] = UNSET
    r"""`[Deprecated]`. The maximum number of tokens that can be generated in the chat completion. This value can be used to control costs for text generated via API.

    This value is now `deprecated` in favor of `max_completion_tokens`, and is not compatible with o1 series models.
    """

    max_completion_tokens: OptionalNullable[int] = UNSET
    r"""An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens"""

    logprobs: OptionalNullable[bool] = UNSET
    r"""Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message."""

    top_logprobs: OptionalNullable[int] = UNSET
    r"""An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used."""

    n: OptionalNullable[int] = UNSET
    r"""How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs."""

    presence_penalty: OptionalNullable[float] = UNSET
    r"""Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics."""

    response_format: Optional[ListPromptVersionsResponseFormat] = None
    r"""An object specifying the format that the model must output"""

    reasoning_effort: Optional[ListPromptVersionsReasoningEffort] = None
    r"""Constrains effort on reasoning for [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.

    - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool calls are supported for all reasoning values in gpt-5.1.
    - All models before `gpt-5.1` default to `medium` reasoning effort, and do not support `none`.
    - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
    - `xhigh` is currently only supported for `gpt-5.1-codex-max`.

    Any of \"none\", \"minimal\", \"low\", \"medium\", \"high\", \"xhigh\".
    """

    verbosity: Optional[str] = None
    r"""Adjusts response verbosity. Lower levels yield shorter answers."""

    seed: OptionalNullable[float] = UNSET
    r"""If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result."""

    stop: OptionalNullable[ListPromptVersionsStop] = UNSET
    r"""Up to 4 sequences where the API will stop generating further tokens."""

    stream_options: OptionalNullable[ListPromptVersionsStreamOptions] = UNSET
    r"""Options for streaming response. Only set this when you set stream: true."""

    thinking: Optional[ListPromptVersionsThinking] = None

    temperature: OptionalNullable[float] = UNSET
    r"""What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic."""

    top_p: OptionalNullable[float] = UNSET
    r"""An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass."""

    top_k: OptionalNullable[float] = UNSET
    r"""Limits the model to consider only the top k most likely tokens at each step."""

    tool_choice: Optional[ListPromptVersionsToolChoice] = None
    r"""Controls which (if any) tool is called by the model."""

    parallel_tool_calls: Optional[bool] = None
    r"""Whether to enable parallel function calling during tool use."""

    modalities: OptionalNullable[List[ListPromptVersionsModalities]] = UNSET
    r"""Output types that you would like the model to generate. Most models are capable of generating text, which is the default: [\"text\"]. The gpt-4o-audio-preview model can also be used to generate audio. To request that this model generate both text and audio responses, you can use: [\"text\", \"audio\"]."""

    guardrails: Optional[List[ListPromptVersionsGuardrails]] = None
    r"""A list of guardrails to apply to the request."""

    fallbacks: Optional[List[ListPromptVersionsFallbacks]] = None
    r"""Array of fallback models to use if primary model fails"""

    retry: Optional[ListPromptVersionsRetry] = None
    r"""Retry configuration for the request"""

    cache: Optional[ListPromptVersionsCache] = None
    r"""Cache configuration for the request."""

    load_balancer: Optional[ListPromptVersionsLoadBalancer] = None
    r"""Load balancer configuration for the request."""

    timeout: Optional[ListPromptVersionsTimeout] = None
    r"""Timeout configuration to apply to the request. If the request exceeds the timeout, it will be retried or fallback to the next model if configured."""

    messages: Optional[List[ListPromptVersionsPromptsMessages]] = None
    r"""Array of messages that make up the conversation. Each message has a role (system, user, assistant, or tool) and content."""

    model: OptionalNullable[str] = UNSET
    r"""Model ID used to generate the response, like `openai/gpt-4o` or `anthropic/claude-3-5-sonnet-20241022`. For private models, use format: `{workspaceKey}@{provider}/{model}`."""

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "audio",
                "frequency_penalty",
                "max_tokens",
                "max_completion_tokens",
                "logprobs",
                "top_logprobs",
                "n",
                "presence_penalty",
                "response_format",
                "reasoning_effort",
                "verbosity",
                "seed",
                "stop",
                "stream_options",
                "thinking",
                "temperature",
                "top_p",
                "top_k",
                "tool_choice",
                "parallel_tool_calls",
                "modalities",
                "guardrails",
                "fallbacks",
                "retry",
                "cache",
                "load_balancer",
                "timeout",
                "messages",
                "model",
                "version",
            ]
        )
        nullable_fields = set(
            [
                "audio",
                "frequency_penalty",
                "max_tokens",
                "max_completion_tokens",
                "logprobs",
                "top_logprobs",
                "n",
                "presence_penalty",
                "seed",
                "stop",
                "stream_options",
                "temperature",
                "top_p",
                "top_k",
                "modalities",
                "model",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ListPromptVersionsUseCases = Literal[
    "Agents simulations",
    "Agents",
    "API interaction",
    "Autonomous Agents",
    "Chatbots",
    "Classification",
    "Code understanding",
    "Code writing",
    "Conversation",
    "Documents QA",
    "Evaluation",
    "Extraction",
    "Multi-modal",
    "Self-checking",
    "Sentiment analysis",
    "SQL",
    "Summarization",
    "Tagging",
    "Translation (document)",
    "Translation (sentences)",
]


ListPromptVersionsLanguage = Literal[
    "Chinese",
    "Dutch",
    "English",
    "French",
    "German",
    "Russian",
    "Spanish",
]
r"""The language that the prompt is written in. Use this field to categorize the prompt for your own purpose"""


class ListPromptVersionsMetadataTypedDict(TypedDict):
    use_cases: NotRequired[List[ListPromptVersionsUseCases]]
    r"""A list of use cases that the prompt is meant to be used for. Use this field to categorize the prompt for your own purpose"""
    language: NotRequired[Nullable[ListPromptVersionsLanguage]]
    r"""The language that the prompt is written in. Use this field to categorize the prompt for your own purpose"""


class ListPromptVersionsMetadata(BaseModel):
    use_cases: Optional[List[ListPromptVersionsUseCases]] = None
    r"""A list of use cases that the prompt is meant to be used for. Use this field to categorize the prompt for your own purpose"""

    language: OptionalNullable[ListPromptVersionsLanguage] = UNSET
    r"""The language that the prompt is written in. Use this field to categorize the prompt for your own purpose"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["use_cases", "language"])
        nullable_fields = set(["language"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ListPromptVersionsDataTypedDict(TypedDict):
    id: str
    prompt: ListPromptVersionsPromptFieldTypedDict
    r"""Prompt configuration with model and messages. Use this instead of prompt_config."""
    timestamp: str
    created_by_id: NotRequired[Nullable[str]]
    updated_by_id: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]
    r"""The prompt’s description, meant to be displayable in the UI. Use this field to optionally store a long form explanation of the prompt for your own purpose"""
    prompt_config: NotRequired[ListPromptVersionsPromptConfigTypedDict]
    r"""[DEPRECATED] Use the `prompt` property instead. A list of messages compatible with the openAI schema."""
    metadata: NotRequired[ListPromptVersionsMetadataTypedDict]


class ListPromptVersionsData(BaseModel):
    id: Annotated[str, pydantic.Field(alias="_id")]

    prompt: ListPromptVersionsPromptField
    r"""Prompt configuration with model and messages. Use this instead of prompt_config."""

    timestamp: str

    created_by_id: OptionalNullable[str] = UNSET

    updated_by_id: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET
    r"""The prompt’s description, meant to be displayable in the UI. Use this field to optionally store a long form explanation of the prompt for your own purpose"""

    prompt_config: Annotated[
        Optional[ListPromptVersionsPromptConfig],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""[DEPRECATED] Use the `prompt` property instead. A list of messages compatible with the openAI schema."""

    metadata: Optional[ListPromptVersionsMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "created_by_id",
                "updated_by_id",
                "description",
                "prompt_config",
                "metadata",
            ]
        )
        nullable_fields = set(["created_by_id", "updated_by_id", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ListPromptVersionsResponseBodyTypedDict(TypedDict):
    r"""Prompt versions retrieved."""

    object: ListPromptVersionsObject
    data: List[ListPromptVersionsDataTypedDict]
    has_more: bool


class ListPromptVersionsResponseBody(BaseModel):
    r"""Prompt versions retrieved."""

    object: ListPromptVersionsObject

    data: List[ListPromptVersionsData]

    has_more: bool
