"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .managementdomain import ManagementDomain, ManagementDomainTypedDict
from orq_ai_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListManagementCapabilitiesResponseTypedDict(TypedDict):
    domains: List[ManagementDomainTypedDict]
    r"""Full management capability catalog."""


class ListManagementCapabilitiesResponse(BaseModel):
    domains: List[ManagementDomain]
    r"""Full management capability catalog."""
