"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatemcpserverrequest import (
    UpdateMcpServerRequest,
    UpdateMcpServerRequestTypedDict,
)
from orq_ai_sdk.types import BaseModel
from orq_ai_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class McpServerUpdateRequestTypedDict(TypedDict):
    id: str
    update_mcp_server_request: UpdateMcpServerRequestTypedDict


class McpServerUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_mcp_server_request: Annotated[
        UpdateMcpServerRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
