"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QueryLogsRequestTypedDict(TypedDict):
    oql: str
    r"""OQL query string, e.g.
    `fetch logs | filter severity_number > 10 | filter body contains \"error\"`.
    """
    from_: datetime
    to: datetime
    limit: NotRequired[int]
    r"""Maximum rows to return; a `| limit N` pipeline command takes precedence."""
    page_token: NotRequired[str]
    r"""Opaque cursor for pagination."""


class QueryLogsRequest(BaseModel):
    oql: str
    r"""OQL query string, e.g.
    `fetch logs | filter severity_number > 10 | filter body contains \"error\"`.
    """

    from_: Annotated[datetime, pydantic.Field(alias="from")]

    to: datetime

    limit: Optional[int] = None
    r"""Maximum rows to return; a `| limit N` pipeline command takes precedence."""

    page_token: Optional[str] = None
    r"""Opaque cursor for pagination."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "page_token"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    QueryLogsRequest.model_rebuild()
except NameError:
    pass
