"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ResponseStartedEventType = Literal["response.started",]


class DataTypedDict(TypedDict):
    response_id: str
    r"""Unique identifier for this response"""
    task_id: str
    r"""The agent execution task ID. Use responseId for tracking instead."""
    model: str
    r"""The model ID being used for this response in provider/model format"""
    workflow_run_id: str
    r"""Trace ID for this turn of the conversation (new for each continuation)"""
    user_message_id: NotRequired[str]
    r"""Server-generated ID for the user message. Use this ID for frontend state consistency."""
    assistant_message_id: NotRequired[str]
    r"""Server-generated ID for the assistant message. Use this ID for frontend state consistency."""


class Data(BaseModel):
    response_id: Annotated[str, pydantic.Field(alias="responseId")]
    r"""Unique identifier for this response"""

    task_id: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.",
            alias="taskId",
        ),
    ]
    r"""The agent execution task ID. Use responseId for tracking instead."""

    model: str
    r"""The model ID being used for this response in provider/model format"""

    workflow_run_id: Annotated[str, pydantic.Field(alias="workflowRunId")]
    r"""Trace ID for this turn of the conversation (new for each continuation)"""

    user_message_id: Annotated[Optional[str], pydantic.Field(alias="userMessageId")] = (
        None
    )
    r"""Server-generated ID for the user message. Use this ID for frontend state consistency."""

    assistant_message_id: Annotated[
        Optional[str], pydantic.Field(alias="assistantMessageId")
    ] = None
    r"""Server-generated ID for the assistant message. Use this ID for frontend state consistency."""


class ResponseStartedEventTypedDict(TypedDict):
    r"""Emitted when the agent begins processing. Contains identifiers for tracking the response."""

    type: ResponseStartedEventType
    timestamp: str
    r"""ISO timestamp of when the event occurred"""
    data: DataTypedDict


class ResponseStartedEvent(BaseModel):
    r"""Emitted when the agent begins processing. Contains identifiers for tracking the response."""

    type: ResponseStartedEventType

    timestamp: str
    r"""ISO timestamp of when the event occurred"""

    data: Data
