"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


RetrieveKnowledgeBasesToolType = Literal["retrieve_knowledge_bases",]


class RetrieveKnowledgeBasesToolTypedDict(TypedDict):
    r"""Lists available knowledge bases"""

    type: RetrieveKnowledgeBasesToolType
    requires_approval: NotRequired[bool]


class RetrieveKnowledgeBasesTool(BaseModel):
    r"""Lists available knowledge bases"""

    type: RetrieveKnowledgeBasesToolType

    requires_approval: Optional[bool] = False
