"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SubmitFeedbackRequestTypedDict(TypedDict):
    message: str
    r"""What happened, what was expected, and steps to reproduce. Do not include secrets."""
    category: str
    request_id: NotRequired[str]
    url: NotRequired[str]


class SubmitFeedbackRequest(BaseModel):
    message: str
    r"""What happened, what was expected, and steps to reproduce. Do not include secrets."""

    category: str

    request_id: Optional[str] = None

    url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["request_id", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
