"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


ToolFailedEventType = Literal["tool.failed",]


class ToolFailedEventDataTypedDict(TypedDict):
    tool_id: str
    r"""Unique identifier for the tool in the tool registry"""
    tool_call_id: str
    r"""Unique identifier matching the tool call that failed"""
    error: str
    r"""Error message describing why the tool failed"""


class ToolFailedEventData(BaseModel):
    tool_id: Annotated[str, pydantic.Field(alias="toolId")]
    r"""Unique identifier for the tool in the tool registry"""

    tool_call_id: Annotated[str, pydantic.Field(alias="toolCallId")]
    r"""Unique identifier matching the tool call that failed"""

    error: str
    r"""Error message describing why the tool failed"""


class ToolFailedEventTypedDict(TypedDict):
    r"""Emitted when a tool execution fails. Contains error details."""

    type: ToolFailedEventType
    timestamp: str
    r"""ISO timestamp of when the event occurred"""
    data: ToolFailedEventDataTypedDict


class ToolFailedEvent(BaseModel):
    r"""Emitted when a tool execution fails. Contains error details."""

    type: ToolFailedEventType

    timestamp: str
    r"""ISO timestamp of when the event occurred"""

    data: ToolFailedEventData


try:
    ToolFailedEventData.model_rebuild()
except NameError:
    pass
