"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ToolExecutionStartedStreamingEventType = Literal[
    "event.workflow_events.tool_execution_started",
]


Product = Literal[
    "remoteconfigs",
    "deployments",
    "experiments",
    "playgrounds",
    "spreadsheets",
    "spreadsheet_run",
    "llm_evaluator",
    "knowledge",
    "router",
    "workflows",
    "external_events",
    "agents",
    "memory-stores",
    "generic",
    "evaluators",
    "otel",
    "ai-chat",
]
r"""Orquesta product"""


class MemoryTypedDict(TypedDict):
    entity_id: str


class Memory(BaseModel):
    entity_id: str


class ToolExecutionContextTypedDict(TypedDict):
    action_id: str
    agent_tool_call_id: str
    workspace_id: str
    agent_manifest_id: str
    agent_execution_id: str
    product: Product
    r"""Orquesta product"""
    memory: NotRequired[MemoryTypedDict]
    parent_id: NotRequired[str]


class ToolExecutionContext(BaseModel):
    action_id: str

    agent_tool_call_id: str

    workspace_id: str

    agent_manifest_id: str

    agent_execution_id: str

    product: Product
    r"""Orquesta product"""

    memory: Optional[Memory] = None

    parent_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["memory", "parent_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ToolExecutionStartedStreamingEventDataTypedDict(TypedDict):
    tool_id: str
    action_type: str
    tool_arguments: Dict[str, Any]
    tool_execution_context: ToolExecutionContextTypedDict
    workflow_run_id: str
    tool_key: NotRequired[str]
    tool_display_name: NotRequired[str]
    tool_description: NotRequired[Nullable[str]]
    response_id: NotRequired[str]
    stream: NotRequired[bool]


class ToolExecutionStartedStreamingEventData(BaseModel):
    tool_id: str

    action_type: str

    tool_arguments: Dict[str, Any]

    tool_execution_context: ToolExecutionContext

    workflow_run_id: Annotated[str, pydantic.Field(alias="workflowRunId")]

    tool_key: Optional[str] = None

    tool_display_name: Optional[str] = None

    tool_description: OptionalNullable[str] = UNSET

    response_id: Annotated[Optional[str], pydantic.Field(alias="responseId")] = None

    stream: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tool_key",
                "tool_display_name",
                "tool_description",
                "responseId",
                "stream",
            ]
        )
        nullable_fields = set(["tool_description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ToolExecutionStartedStreamingEventTypedDict(TypedDict):
    r"""Emitted when a tool begins execution. Contains the tool ID, name, action type, input arguments, and execution context."""

    type: ToolExecutionStartedStreamingEventType
    timestamp: str
    r"""ISO timestamp of the event"""
    data: ToolExecutionStartedStreamingEventDataTypedDict


class ToolExecutionStartedStreamingEvent(BaseModel):
    r"""Emitted when a tool begins execution. Contains the tool ID, name, action type, input arguments, and execution context."""

    type: ToolExecutionStartedStreamingEventType

    timestamp: str
    r"""ISO timestamp of the event"""

    data: ToolExecutionStartedStreamingEventData
