"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .traceagent import TraceAgent, TraceAgentTypedDict
from .tracecontext import TraceContext, TraceContextTypedDict
from .tracecost import TraceCost, TraceCostTypedDict
from .traceusage import TraceUsage, TraceUsageTypedDict
from datetime import datetime
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


TraceSummaryObject = Literal["trace",]
r"""Object discriminator; always `trace`."""


class AttributesTypedDict(TypedDict):
    pass


class Attributes(BaseModel):
    pass


class TraceSummaryTypedDict(TypedDict):
    object: NotRequired[TraceSummaryObject]
    r"""Object discriminator; always `trace`."""
    trace_id: NotRequired[str]
    root_span_id: NotRequired[str]
    leading_span_id: NotRequired[str]
    name: NotRequired[str]
    operation: NotRequired[str]
    status: NotRequired[str]
    started_at: NotRequired[datetime]
    ended_at: NotRequired[datetime]
    duration_ms: NotRequired[float]
    project_id: NotRequired[str]
    identity_id: NotRequired[str]
    session_id: NotRequired[str]
    thread_id: NotRequired[str]
    product: NotRequired[str]
    providers: NotRequired[List[str]]
    models: NotRequired[List[str]]
    agent: NotRequired[TraceAgentTypedDict]
    usage: NotRequired[TraceUsageTypedDict]
    cost: NotRequired[TraceCostTypedDict]
    id: NotRequired[str]
    span_id: NotRequired[str]
    parent_id: NotRequired[str]
    type: NotRequired[str]
    context: NotRequired[TraceContextTypedDict]
    attributes: NotRequired[AttributesTypedDict]
    start_time: NotRequired[datetime]
    end_time: NotRequired[datetime]
    duration: NotRequired[float]


class TraceSummary(BaseModel):
    object: Optional[TraceSummaryObject] = None
    r"""Object discriminator; always `trace`."""

    trace_id: Optional[str] = None

    root_span_id: Optional[str] = None

    leading_span_id: Optional[str] = None

    name: Optional[str] = None

    operation: Optional[str] = None

    status: Optional[str] = None

    started_at: Optional[datetime] = None

    ended_at: Optional[datetime] = None

    duration_ms: Optional[float] = None

    project_id: Optional[str] = None

    identity_id: Optional[str] = None

    session_id: Optional[str] = None

    thread_id: Optional[str] = None

    product: Optional[str] = None

    providers: Optional[List[str]] = None

    models: Optional[List[str]] = None

    agent: Optional[TraceAgent] = None

    usage: Optional[TraceUsage] = None

    cost: Optional[TraceCost] = None

    id: Optional[str] = None

    span_id: Optional[str] = None

    parent_id: Optional[str] = None

    type: Optional[str] = None

    context: Optional[TraceContext] = None

    attributes: Optional[Attributes] = None

    start_time: Optional[datetime] = None

    end_time: Optional[datetime] = None

    duration: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "object",
                "trace_id",
                "root_span_id",
                "leading_span_id",
                "name",
                "operation",
                "status",
                "started_at",
                "ended_at",
                "duration_ms",
                "project_id",
                "identity_id",
                "session_id",
                "thread_id",
                "product",
                "providers",
                "models",
                "agent",
                "usage",
                "cost",
                "id",
                "span_id",
                "parent_id",
                "type",
                "context",
                "attributes",
                "start_time",
                "end_time",
                "duration",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
