"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from orq_ai_sdk import models as models_, utils
from orq_ai_sdk._hooks import HookContext
from orq_ai_sdk.types import OptionalNullable, UNSET
from orq_ai_sdk.utils import get_security_from_env
from orq_ai_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional


class SmartRouters(BaseSDK):
    def list(
        self,
        *,
        limit: Optional[int] = None,
        starting_after: Optional[str] = None,
        ending_before: Optional[str] = None,
        search: Optional[str] = None,
        profile: Optional[Iterable[models_.SmartRouterProfile]] = None,
        enabled: Optional[bool] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.ListSmartRoutersResponse:
        r"""List Smart Routers

        Returns Smart Routers in the caller's workspace, ordered newest first. Supports cursor pagination, name search, profile filtering, and enabled-state filtering.

        :param limit:
        :param starting_after:
        :param ending_before:
        :param search:
        :param profile:
        :param enabled:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterListRequest(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            profile=utils.unmarshal(
                profile, Optional[List[models_.SmartRouterProfile]]
            ),
            enabled=enabled,
        )

        req = self._build_request(
            method="GET",
            path="/v2/smart-routers",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterList",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - List Smart Routers",
                            "lang": "curl",
                            "source": "curl --get 'https://api.orq.ai/v2/smart-routers' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --data-urlencode 'limit=25'\n",
                        },
                        {
                            "label": "Node.js - List Smart Routers",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst page = await client.smartRouters.list({ limit: 25 });\n\nfor (const router of page.data) {\n  console.log(router.key, router.profile);\n}\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.ListSmartRoutersResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        limit: Optional[int] = None,
        starting_after: Optional[str] = None,
        ending_before: Optional[str] = None,
        search: Optional[str] = None,
        profile: Optional[Iterable[models_.SmartRouterProfile]] = None,
        enabled: Optional[bool] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.ListSmartRoutersResponse:
        r"""List Smart Routers

        Returns Smart Routers in the caller's workspace, ordered newest first. Supports cursor pagination, name search, profile filtering, and enabled-state filtering.

        :param limit:
        :param starting_after:
        :param ending_before:
        :param search:
        :param profile:
        :param enabled:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterListRequest(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            search=search,
            profile=utils.unmarshal(
                profile, Optional[List[models_.SmartRouterProfile]]
            ),
            enabled=enabled,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/smart-routers",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterList",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - List Smart Routers",
                            "lang": "curl",
                            "source": "curl --get 'https://api.orq.ai/v2/smart-routers' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --data-urlencode 'limit=25'\n",
                        },
                        {
                            "label": "Node.js - List Smart Routers",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst page = await client.smartRouters.list({ limit: 25 });\n\nfor (const router of page.data) {\n  console.log(router.key, router.profile);\n}\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.ListSmartRoutersResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    def create(
        self,
        *,
        key: str,
        models: Iterable[str],
        profile: models_.SmartRouterProfile,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.CreateSmartRouterResponse:
        r"""Create a Smart Router

        Creates a workspace Smart Router from an ordered pool of autorouter-eligible models. The router key becomes the stable model identifier used by gateway requests.

        :param key: Required. Stable lowercase key containing letters, numbers, and hyphens.
        :param models: Required. Ordered pool of distinct models in provider/model format.
        :param profile:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.CreateSmartRouterRequest(
            key=key,
            models=utils.unmarshal(models, List[str]),
            profile=profile,
        )

        req = self._build_request(
            method="POST",
            path="/v2/smart-routers",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models_.CreateSmartRouterRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterCreate",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Create a Smart Router",
                            "lang": "curl",
                            "source": 'curl --request POST \\\n  --url \'https://api.orq.ai/v2/smart-routers\' \\\n  --header \'Authorization: Bearer $ORQ_API_KEY\' \\\n  --header \'Content-Type: application/json\' \\\n  --data \'{\n    "key": "production-assistant",\n    "models": [\n      "anthropic/claude-opus-4-1",\n      "anthropic/claude-sonnet-4",\n      "openai/gpt-4o-mini"\n    ],\n    "profile": "SMART_ROUTER_PROFILE_QUALITY"\n  }\'\n',
                        },
                        {
                            "label": "Node.js - Create a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst result = await client.smartRouters.create({\n  key: 'production-assistant',\n  models: [\n    'anthropic/claude-opus-4-1',\n    'anthropic/claude-sonnet-4',\n    'openai/gpt-4o-mini',\n  ],\n  profile: 'SMART_ROUTER_PROFILE_QUALITY',\n});\n\nconsole.log(result.smartRouter.modelRef);\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.CreateSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def create_async(
        self,
        *,
        key: str,
        models: Iterable[str],
        profile: models_.SmartRouterProfile,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.CreateSmartRouterResponse:
        r"""Create a Smart Router

        Creates a workspace Smart Router from an ordered pool of autorouter-eligible models. The router key becomes the stable model identifier used by gateway requests.

        :param key: Required. Stable lowercase key containing letters, numbers, and hyphens.
        :param models: Required. Ordered pool of distinct models in provider/model format.
        :param profile:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.CreateSmartRouterRequest(
            key=key,
            models=utils.unmarshal(models, List[str]),
            profile=profile,
        )

        req = self._build_request_async(
            method="POST",
            path="/v2/smart-routers",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models_.CreateSmartRouterRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterCreate",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Create a Smart Router",
                            "lang": "curl",
                            "source": 'curl --request POST \\\n  --url \'https://api.orq.ai/v2/smart-routers\' \\\n  --header \'Authorization: Bearer $ORQ_API_KEY\' \\\n  --header \'Content-Type: application/json\' \\\n  --data \'{\n    "key": "production-assistant",\n    "models": [\n      "anthropic/claude-opus-4-1",\n      "anthropic/claude-sonnet-4",\n      "openai/gpt-4o-mini"\n    ],\n    "profile": "SMART_ROUTER_PROFILE_QUALITY"\n  }\'\n',
                        },
                        {
                            "label": "Node.js - Create a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst result = await client.smartRouters.create({\n  key: 'production-assistant',\n  models: [\n    'anthropic/claude-opus-4-1',\n    'anthropic/claude-sonnet-4',\n    'openai/gpt-4o-mini',\n  ],\n  profile: 'SMART_ROUTER_PROFILE_QUALITY',\n});\n\nconsole.log(result.smartRouter.modelRef);\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.CreateSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    def get(
        self,
        *,
        smart_router_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.GetSmartRouterResponse:
        r"""Retrieve a Smart Router

        Retrieves a Smart Router by ID within the caller's workspace.

        :param smart_router_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterGetRequest(
            smart_router_id=smart_router_id,
        )

        req = self._build_request(
            method="GET",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterGet",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Retrieve a Smart Router",
                            "lang": "curl",
                            "source": "curl --request GET \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY'\n",
                        },
                        {
                            "label": "Node.js - Retrieve a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst result = await client.smartRouters.get({\n  smartRouterId: '019d-smart-router-id',\n});\n\nconsole.log(result.smartRouter.key);\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.GetSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def get_async(
        self,
        *,
        smart_router_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.GetSmartRouterResponse:
        r"""Retrieve a Smart Router

        Retrieves a Smart Router by ID within the caller's workspace.

        :param smart_router_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterGetRequest(
            smart_router_id=smart_router_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterGet",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Retrieve a Smart Router",
                            "lang": "curl",
                            "source": "curl --request GET \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY'\n",
                        },
                        {
                            "label": "Node.js - Retrieve a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nconst result = await client.smartRouters.get({\n  smartRouterId: '019d-smart-router-id',\n});\n\nconsole.log(result.smartRouter.key);\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.GetSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    def delete(
        self,
        *,
        smart_router_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.DeleteSmartRouterResponse:
        r"""Delete a Smart Router

        Permanently deletes a Smart Router and removes its gateway model configuration.

        :param smart_router_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterDeleteRequest(
            smart_router_id=smart_router_id,
        )

        req = self._build_request(
            method="DELETE",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterDelete",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Delete a Smart Router",
                            "lang": "curl",
                            "source": "curl --request DELETE \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY'\n",
                        },
                        {
                            "label": "Node.js - Delete a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.delete({\n  smartRouterId: '019d-smart-router-id',\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.DeleteSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def delete_async(
        self,
        *,
        smart_router_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.DeleteSmartRouterResponse:
        r"""Delete a Smart Router

        Permanently deletes a Smart Router and removes its gateway model configuration.

        :param smart_router_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterDeleteRequest(
            smart_router_id=smart_router_id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterDelete",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Delete a Smart Router",
                            "lang": "curl",
                            "source": "curl --request DELETE \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY'\n",
                        },
                        {
                            "label": "Node.js - Delete a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.delete({\n  smartRouterId: '019d-smart-router-id',\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.DeleteSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    def update(
        self,
        *,
        smart_router_id: str,
        models: Optional[Iterable[str]] = None,
        profile: Optional[models_.SmartRouterProfile] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.UpdateSmartRouterResponse:
        r"""Update a Smart Router

        Partially updates the routing models or profile. The router key is immutable.

        :param smart_router_id:
        :param models:
        :param profile:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterUpdateRequest(
            smart_router_id=smart_router_id,
            update_smart_router_request=models_.UpdateSmartRouterRequest(
                models=utils.unmarshal(models, Optional[List[str]]),
                profile=profile,
            ),
        )

        req = self._build_request(
            method="PATCH",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.update_smart_router_request,
                False,
                False,
                "json",
                models_.UpdateSmartRouterRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterUpdate",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Update a Smart Router",
                            "lang": "curl",
                            "source": "curl --request PATCH \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\"profile\":\"SMART_ROUTER_PROFILE_COST\"}'\n",
                        },
                        {
                            "label": "Node.js - Update a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.update({\n  smartRouterId: '019d-smart-router-id',\n  profile: 'SMART_ROUTER_PROFILE_COST',\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.UpdateSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def update_async(
        self,
        *,
        smart_router_id: str,
        models: Optional[Iterable[str]] = None,
        profile: Optional[models_.SmartRouterProfile] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.UpdateSmartRouterResponse:
        r"""Update a Smart Router

        Partially updates the routing models or profile. The router key is immutable.

        :param smart_router_id:
        :param models:
        :param profile:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterUpdateRequest(
            smart_router_id=smart_router_id,
            update_smart_router_request=models_.UpdateSmartRouterRequest(
                models=utils.unmarshal(models, Optional[List[str]]),
                profile=profile,
            ),
        )

        req = self._build_request_async(
            method="PATCH",
            path="/v2/smart-routers/{smart_router_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.update_smart_router_request,
                False,
                False,
                "json",
                models_.UpdateSmartRouterRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterUpdate",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Update a Smart Router",
                            "lang": "curl",
                            "source": "curl --request PATCH \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\"profile\":\"SMART_ROUTER_PROFILE_COST\"}'\n",
                        },
                        {
                            "label": "Node.js - Update a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.update({\n  smartRouterId: '019d-smart-router-id',\n  profile: 'SMART_ROUTER_PROFILE_COST',\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.UpdateSmartRouterResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    def set_enabled(
        self,
        *,
        smart_router_id: str,
        enabled: bool,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.SetSmartRouterEnabledResponse:
        r"""Enable or disable a Smart Router

        Controls whether the Smart Router is available to gateway requests in the workspace.

        :param smart_router_id:
        :param enabled:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterSetEnabledRequest(
            smart_router_id=smart_router_id,
            set_smart_router_enabled_request=models_.SetSmartRouterEnabledRequest(
                enabled=enabled,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v2/smart-routers/{smart_router_id}/enabled",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.set_smart_router_enabled_request,
                False,
                False,
                "json",
                models_.SetSmartRouterEnabledRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterSetEnabled",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Disable a Smart Router",
                            "lang": "curl",
                            "source": "curl --request POST \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id/enabled' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\"enabled\":false}'\n",
                        },
                        {
                            "label": "Node.js - Disable a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.setEnabled({\n  smartRouterId: '019d-smart-router-id',\n  enabled: false,\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models_.SetSmartRouterEnabledResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)

    async def set_enabled_async(
        self,
        *,
        smart_router_id: str,
        enabled: bool,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models_.SetSmartRouterEnabledResponse:
        r"""Enable or disable a Smart Router

        Controls whether the Smart Router is available to gateway requests in the workspace.

        :param smart_router_id:
        :param enabled:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if timeout_ms is None:
            timeout_ms = 600000

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models_.SmartRouterSetEnabledRequest(
            smart_router_id=smart_router_id,
            set_smart_router_enabled_request=models_.SetSmartRouterEnabledRequest(
                enabled=enabled,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v2/smart-routers/{smart_router_id}/enabled",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.set_smart_router_enabled_request,
                False,
                False,
                "json",
                models_.SetSmartRouterEnabledRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="SmartRouterSetEnabled",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["Smart Routers"],
                extensions={
                    "x-code-samples": [
                        {
                            "label": "Core - Disable a Smart Router",
                            "lang": "curl",
                            "source": "curl --request POST \\\n  --url 'https://api.orq.ai/v2/smart-routers/019d-smart-router-id/enabled' \\\n  --header 'Authorization: Bearer $ORQ_API_KEY' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\"enabled\":false}'\n",
                        },
                        {
                            "label": "Node.js - Disable a Smart Router",
                            "lang": "typescript",
                            "source": "import { Orq } from '@orq-ai/node';\n\nconst client = new Orq({ apiKey: process.env.ORQ_API_KEY });\nawait client.smartRouters.setEnabled({\n  smartRouterId: '019d-smart-router-id',\n  enabled: false,\n});\n",
                        },
                    ]
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models_.SetSmartRouterEnabledResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.APIError("API error occurred", http_res, http_res_text)

        raise models_.APIError("Unexpected response received", http_res)
