"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .auditlogfilter import AuditLogFilter, AuditLogFilterTypedDict
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AuditLogFilterQueryTypedDict(TypedDict):
    r"""Search and advanced filters for querying audit logs."""

    operator: str
    r"""Logical operator used to combine filters."""
    filters: List[AuditLogFilterTypedDict]
    r"""Advanced filters applied to the query."""
    search: NotRequired[str]
    r"""Optional text search applied to supported display fields."""


class AuditLogFilterQuery(BaseModel):
    r"""Search and advanced filters for querying audit logs."""

    operator: str
    r"""Logical operator used to combine filters."""

    filters: List[AuditLogFilter]
    r"""Advanced filters applied to the query."""

    search: Optional[str] = None
    r"""Optional text search applied to supported display fields."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
