"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Literal, Optional
from typing_extensions import NotRequired, TypedDict


ClassifyAnswerType = Literal[
    "noul",
    "choice",
    "score",
]
r"""The question type this answer belongs to."""


class ClassifyAnswerTypedDict(TypedDict):
    type: ClassifyAnswerType
    r"""The question type this answer belongs to."""
    choice: NotRequired[str]
    r"""The selected option. Present for choice answers."""
    confidence: NotRequired[float]
    r"""Probability of the selected option or level. Present for choice and score answers."""
    legend: NotRequired[Dict[str, str]]
    r"""Level index to level description. Present for score answers."""
    noul: NotRequired[float]
    r"""Probability between 0 and 1 that the statement holds. Present for noul answers."""
    probabilities: NotRequired[Dict[str, float]]
    r"""Probability distribution over the options or levels. Present for choice and score answers."""
    score: NotRequired[float]
    r"""The selected level index. Present for score answers."""


class ClassifyAnswer(BaseModel):
    type: ClassifyAnswerType
    r"""The question type this answer belongs to."""

    choice: Optional[str] = None
    r"""The selected option. Present for choice answers."""

    confidence: Optional[float] = None
    r"""Probability of the selected option or level. Present for choice and score answers."""

    legend: Optional[Dict[str, str]] = None
    r"""Level index to level description. Present for score answers."""

    noul: Optional[float] = None
    r"""Probability between 0 and 1 that the statement holds. Present for noul answers."""

    probabilities: Optional[Dict[str, float]] = None
    r"""Probability distribution over the options or levels. Present for choice and score answers."""

    score: Optional[float] = None
    r"""The selected level index. Present for score answers."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["choice", "confidence", "legend", "noul", "probabilities", "score"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
