"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from orq_ai_sdk.utils import get_discriminator
import pydantic
from pydantic import ConfigDict, Discriminator, Tag, model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CreateToolRequestBodyToolsRequestStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolRequestBodyToolsRequest4Type = Literal["code",]


CreateToolRequestBodyToolsRequest4CodeToolType = Literal["object",]
r"""The type must be \"object\" """


class CreateToolRequestBodyParametersTypedDict(TypedDict):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: CreateToolRequestBodyToolsRequest4CodeToolType
    r"""The type must be \"object\" """
    properties: Dict[str, Any]
    r"""The properties of the function parameters"""
    required: List[str]
    r"""Array of required parameter names"""


class CreateToolRequestBodyParameters(BaseModel):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: CreateToolRequestBodyToolsRequest4CodeToolType
    r"""The type must be \"object\" """

    properties: Dict[str, Any]
    r"""The properties of the function parameters"""

    required: List[str]
    r"""Array of required parameter names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


RequestBodyLanguage = Literal["python",]


class RequestBodyCodeToolTypedDict(TypedDict):
    language: RequestBodyLanguage
    code: str
    r"""The code to execute."""
    parameters: NotRequired[CreateToolRequestBodyParametersTypedDict]
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""


class RequestBodyCodeTool(BaseModel):
    language: RequestBodyLanguage

    code: str
    r"""The code to execute."""

    parameters: Optional[CreateToolRequestBodyParameters] = None
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CodeExecutionToolTypedDict(TypedDict):
    r"""Executes code snippets in a sandboxed environment, currently supporting Python."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    type: CreateToolRequestBodyToolsRequest4Type
    code_tool: RequestBodyCodeToolTypedDict
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    status: NotRequired[CreateToolRequestBodyToolsRequestStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class CodeExecutionTool(BaseModel):
    r"""Executes code snippets in a sandboxed environment, currently supporting Python."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    type: CreateToolRequestBodyToolsRequest4Type

    code_tool: RequestBodyCodeTool

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    status: Optional[CreateToolRequestBodyToolsRequestStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateToolRequestBodyToolsStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolRequestBodyToolsRequestType = Literal["http",]


RequestBodyMethod = Literal[
    "GET",
    "POST",
    "PUT",
    "DELETE",
]
r"""The HTTP method to use."""


class CreateToolHeaders2TypedDict(TypedDict):
    value: str
    encrypted: NotRequired[bool]


class CreateToolHeaders2(BaseModel):
    value: str

    encrypted: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["encrypted"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


RequestBodyHeadersTypedDict = TypeAliasType(
    "RequestBodyHeadersTypedDict", Union[CreateToolHeaders2TypedDict, str]
)


RequestBodyHeaders = TypeAliasType("RequestBodyHeaders", Union[CreateToolHeaders2, str])


class RequestBodyBlueprintTypedDict(TypedDict):
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    url: str
    r"""The URL to send the request to."""
    method: RequestBodyMethod
    r"""The HTTP method to use."""
    headers: NotRequired[Dict[str, RequestBodyHeadersTypedDict]]
    r"""The headers to send with the request. Can be a string value or an object with value and encrypted properties."""
    body: NotRequired[Dict[str, Any]]
    r"""The body to send with the request."""
    timeout: NotRequired[float]
    r"""The request timeout in seconds. Defaults to 60 seconds when not set. When used in an agent, tool executions are also bound by the agent run `limits.tool_timeout` (default 5 minutes), so raise that limit for longer-running tools."""


class RequestBodyBlueprint(BaseModel):
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    url: str
    r"""The URL to send the request to."""

    method: RequestBodyMethod
    r"""The HTTP method to use."""

    headers: Optional[Dict[str, RequestBodyHeaders]] = None
    r"""The headers to send with the request. Can be a string value or an object with value and encrypted properties."""

    body: Optional[Dict[str, Any]] = None
    r"""The body to send with the request."""

    timeout: Optional[float] = None
    r"""The request timeout in seconds. Defaults to 60 seconds when not set. When used in an agent, tool executions are also bound by the agent run `limits.tool_timeout` (default 5 minutes), so raise that limit for longer-running tools."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["headers", "body", "timeout"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateToolRequestBodyToolsRequest3Type = Literal[
    "string",
    "number",
    "boolean",
]
r"""The type of the argument."""


RequestBodyDefaultValueTypedDict = TypeAliasType(
    "RequestBodyDefaultValueTypedDict", Union[str, float, bool]
)
r"""The default value of the argument."""


RequestBodyDefaultValue = TypeAliasType(
    "RequestBodyDefaultValue", Union[str, float, bool]
)
r"""The default value of the argument."""


class RequestBodyArgumentsTypedDict(TypedDict):
    type: CreateToolRequestBodyToolsRequest3Type
    r"""The type of the argument."""
    description: str
    r"""A description of the argument."""
    send_to_model: NotRequired[bool]
    r"""Whether to send the argument to the model. If set to false, the argument will not be sent to the model and needs to be provided by the user or it will be left blank."""
    default_value: NotRequired[RequestBodyDefaultValueTypedDict]
    r"""The default value of the argument."""


class RequestBodyArguments(BaseModel):
    type: CreateToolRequestBodyToolsRequest3Type
    r"""The type of the argument."""

    description: str
    r"""A description of the argument."""

    send_to_model: Optional[bool] = True
    r"""Whether to send the argument to the model. If set to false, the argument will not be sent to the model and needs to be provided by the user or it will be left blank."""

    default_value: Optional[RequestBodyDefaultValue] = None
    r"""The default value of the argument."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["send_to_model", "default_value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RequestBodyHTTPTypedDict(TypedDict):
    blueprint: RequestBodyBlueprintTypedDict
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""
    arguments: NotRequired[Dict[str, RequestBodyArgumentsTypedDict]]
    r"""The arguments to send with the request. The keys will be used to replace the placeholders in the `blueprint` field."""


class RequestBodyHTTP(BaseModel):
    blueprint: RequestBodyBlueprint
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    arguments: Optional[Dict[str, RequestBodyArguments]] = None
    r"""The arguments to send with the request. The keys will be used to replace the placeholders in the `blueprint` field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["arguments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HTTPToolTypedDict(TypedDict):
    r"""Executes HTTP requests to interact with external APIs and web services using customizable blueprints."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    type: CreateToolRequestBodyToolsRequestType
    http: RequestBodyHTTPTypedDict
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    status: NotRequired[CreateToolRequestBodyToolsStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class HTTPTool(BaseModel):
    r"""Executes HTTP requests to interact with external APIs and web services using customizable blueprints."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    type: CreateToolRequestBodyToolsRequestType

    http: RequestBodyHTTP

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    status: Optional[CreateToolRequestBodyToolsStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateToolRequestBodyStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolRequestBodyToolsType = Literal["json_schema",]


class RequestBodySchemaTypedDict(TypedDict):
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: str
    r"""The JSON Schema type"""
    properties: Dict[str, Any]
    r"""The properties of the JSON Schema object"""
    required: List[str]
    r"""Array of required property names"""


class RequestBodySchema(BaseModel):
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: str
    r"""The JSON Schema type"""

    properties: Dict[str, Any]
    r"""The properties of the JSON Schema object"""

    required: List[str]
    r"""Array of required property names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class RequestBodyJSONSchemaTypedDict(TypedDict):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    description: str
    r"""A description of what the response format is for. This will be shown to the user."""
    schema_: RequestBodySchemaTypedDict
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""
    strict: NotRequired[bool]
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. Only compatible with `OpenAI` models."""


class RequestBodyJSONSchema(BaseModel):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""

    description: str
    r"""A description of what the response format is for. This will be shown to the user."""

    schema_: Annotated[RequestBodySchema, pydantic.Field(alias="schema")]
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    strict: Optional[bool] = None
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. Only compatible with `OpenAI` models."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["strict"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class JSONSchemaToolTypedDict(TypedDict):
    r"""A tool that enforces structured output format using JSON Schema for consistent response formatting."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    type: CreateToolRequestBodyToolsType
    json_schema: RequestBodyJSONSchemaTypedDict
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    status: NotRequired[CreateToolRequestBodyStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class JSONSchemaTool(BaseModel):
    r"""A tool that enforces structured output format using JSON Schema for consistent response formatting."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    type: CreateToolRequestBodyToolsType

    json_schema: RequestBodyJSONSchema

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    status: Optional[CreateToolRequestBodyStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


RequestBodyStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolRequestBodyType = Literal["function",]


CreateToolRequestBodyToolsRequest1Type = Literal["object",]
r"""The type must be \"object\" """


class RequestBodyParametersTypedDict(TypedDict):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: CreateToolRequestBodyToolsRequest1Type
    r"""The type must be \"object\" """
    properties: Dict[str, Any]
    r"""The properties of the function parameters"""
    required: List[str]
    r"""Array of required parameter names"""


class RequestBodyParameters(BaseModel):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: CreateToolRequestBodyToolsRequest1Type
    r"""The type must be \"object\" """

    properties: Dict[str, Any]
    r"""The properties of the function parameters"""

    required: List[str]
    r"""Array of required parameter names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class RequestBodyFunctionTypedDict(TypedDict):
    name: str
    r"""The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    description: NotRequired[str]
    r"""A description of what the function does, used by the model to choose when and how to call the function."""
    strict: NotRequired[bool]
    r"""Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Currently only compatible with `OpenAI` models."""
    parameters: NotRequired[RequestBodyParametersTypedDict]
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""


class RequestBodyFunction(BaseModel):
    name: str
    r"""The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""

    description: Optional[str] = None
    r"""A description of what the function does, used by the model to choose when and how to call the function."""

    strict: Optional[bool] = None
    r"""Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Currently only compatible with `OpenAI` models."""

    parameters: Optional[RequestBodyParameters] = None
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "strict", "parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FunctionToolTypedDict(TypedDict):
    r"""A custom function tool that allows the model to call predefined functions with structured parameters."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    type: CreateToolRequestBodyType
    function: RequestBodyFunctionTypedDict
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    status: NotRequired[RequestBodyStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class FunctionTool(BaseModel):
    r"""A custom function tool that allows the model to call predefined functions with structured parameters."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    type: CreateToolRequestBodyType

    function: RequestBodyFunction

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    status: Optional[RequestBodyStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateToolRequestBodyTypedDict = TypeAliasType(
    "CreateToolRequestBodyTypedDict",
    Union[
        FunctionToolTypedDict,
        JSONSchemaToolTypedDict,
        HTTPToolTypedDict,
        CodeExecutionToolTypedDict,
    ],
)
r"""The tool to create"""


CreateToolRequestBody = Annotated[
    Union[
        Annotated[FunctionTool, Tag("function")],
        Annotated[JSONSchemaTool, Tag("json_schema")],
        Annotated[HTTPTool, Tag("http")],
        Annotated[CodeExecutionTool, Tag("code")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""The tool to create"""


CreateToolResponseBodyToolsResponseStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolResponseBodyToolsResponse200Type = Literal["code",]


CreateToolResponseBodyToolsResponse200ApplicationJSON4Type = Literal["object",]
r"""The type must be \"object\" """


class CreateToolResponseBodyParametersTypedDict(TypedDict):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: CreateToolResponseBodyToolsResponse200ApplicationJSON4Type
    r"""The type must be \"object\" """
    properties: Dict[str, Any]
    r"""The properties of the function parameters"""
    required: List[str]
    r"""Array of required parameter names"""


class CreateToolResponseBodyParameters(BaseModel):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: CreateToolResponseBodyToolsResponse200ApplicationJSON4Type
    r"""The type must be \"object\" """

    properties: Dict[str, Any]
    r"""The properties of the function parameters"""

    required: List[str]
    r"""Array of required parameter names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


ResponseBodyLanguage = Literal["python",]


class ResponseBodyCodeToolTypedDict(TypedDict):
    language: ResponseBodyLanguage
    code: str
    r"""The code to execute."""
    parameters: NotRequired[CreateToolResponseBodyParametersTypedDict]
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""


class ResponseBodyCodeTool(BaseModel):
    language: ResponseBodyLanguage

    code: str
    r"""The code to execute."""

    parameters: Optional[CreateToolResponseBodyParameters] = None
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseBodyCodeExecutionToolTypedDict(TypedDict):
    r"""Executes code snippets in a sandboxed environment, currently supporting Python."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    project_id: str
    workspace_id: str
    created: str
    updated: str
    type: CreateToolResponseBodyToolsResponse200Type
    code_tool: ResponseBodyCodeToolTypedDict
    id: NotRequired[str]
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    created_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that created the tool"""
    updated_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that last updated the tool"""
    status: NotRequired[CreateToolResponseBodyToolsResponseStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class ResponseBodyCodeExecutionTool(BaseModel):
    r"""Executes code snippets in a sandboxed environment, currently supporting Python."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    project_id: str

    workspace_id: str

    created: str

    updated: str

    type: CreateToolResponseBodyToolsResponse200Type

    code_tool: ResponseBodyCodeTool

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = (
        "tool_01M1D09ENGN4HWZ5ZR2H19PP3B"
    )

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    created_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that created the tool"""

    updated_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that last updated the tool"""

    status: Optional[CreateToolResponseBodyToolsResponseStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_id", "display_name", "created_by_id", "updated_by_id", "status"]
        )
        nullable_fields = set(["created_by_id", "updated_by_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


CreateToolResponseBodyToolsStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolResponseBodyToolsResponseType = Literal["http",]


CreateToolResponseBodyMethod = Literal[
    "GET",
    "POST",
    "PUT",
    "DELETE",
]
r"""The HTTP method to use."""


class CreateToolHeadersTools2TypedDict(TypedDict):
    value: str
    encrypted: NotRequired[bool]


class CreateToolHeadersTools2(BaseModel):
    value: str

    encrypted: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["encrypted"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ResponseBodyHeadersTypedDict = TypeAliasType(
    "ResponseBodyHeadersTypedDict", Union[CreateToolHeadersTools2TypedDict, str]
)


ResponseBodyHeaders = TypeAliasType(
    "ResponseBodyHeaders", Union[CreateToolHeadersTools2, str]
)


class ResponseBodyBlueprintTypedDict(TypedDict):
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    url: str
    r"""The URL to send the request to."""
    method: CreateToolResponseBodyMethod
    r"""The HTTP method to use."""
    headers: NotRequired[Dict[str, ResponseBodyHeadersTypedDict]]
    r"""The headers to send with the request. Can be a string value or an object with value and encrypted properties."""
    body: NotRequired[Dict[str, Any]]
    r"""The body to send with the request."""
    timeout: NotRequired[float]
    r"""The request timeout in seconds. Defaults to 60 seconds when not set. When used in an agent, tool executions are also bound by the agent run `limits.tool_timeout` (default 5 minutes), so raise that limit for longer-running tools."""


class ResponseBodyBlueprint(BaseModel):
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    url: str
    r"""The URL to send the request to."""

    method: CreateToolResponseBodyMethod
    r"""The HTTP method to use."""

    headers: Optional[Dict[str, ResponseBodyHeaders]] = None
    r"""The headers to send with the request. Can be a string value or an object with value and encrypted properties."""

    body: Optional[Dict[str, Any]] = None
    r"""The body to send with the request."""

    timeout: Optional[float] = None
    r"""The request timeout in seconds. Defaults to 60 seconds when not set. When used in an agent, tool executions are also bound by the agent run `limits.tool_timeout` (default 5 minutes), so raise that limit for longer-running tools."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["headers", "body", "timeout"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreateToolResponseBodyToolsResponse200ApplicationJSONType = Literal[
    "string",
    "number",
    "boolean",
]
r"""The type of the argument."""


ResponseBodyDefaultValueTypedDict = TypeAliasType(
    "ResponseBodyDefaultValueTypedDict", Union[str, float, bool]
)
r"""The default value of the argument."""


ResponseBodyDefaultValue = TypeAliasType(
    "ResponseBodyDefaultValue", Union[str, float, bool]
)
r"""The default value of the argument."""


class ResponseBodyArgumentsTypedDict(TypedDict):
    type: CreateToolResponseBodyToolsResponse200ApplicationJSONType
    r"""The type of the argument."""
    description: str
    r"""A description of the argument."""
    send_to_model: NotRequired[bool]
    r"""Whether to send the argument to the model. If set to false, the argument will not be sent to the model and needs to be provided by the user or it will be left blank."""
    default_value: NotRequired[ResponseBodyDefaultValueTypedDict]
    r"""The default value of the argument."""


class ResponseBodyArguments(BaseModel):
    type: CreateToolResponseBodyToolsResponse200ApplicationJSONType
    r"""The type of the argument."""

    description: str
    r"""A description of the argument."""

    send_to_model: Optional[bool] = True
    r"""Whether to send the argument to the model. If set to false, the argument will not be sent to the model and needs to be provided by the user or it will be left blank."""

    default_value: Optional[ResponseBodyDefaultValue] = None
    r"""The default value of the argument."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["send_to_model", "default_value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateToolResponseBodyHTTPTypedDict(TypedDict):
    blueprint: ResponseBodyBlueprintTypedDict
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""
    arguments: NotRequired[Dict[str, ResponseBodyArgumentsTypedDict]]
    r"""The arguments to send with the request. The keys will be used to replace the placeholders in the `blueprint` field."""


class CreateToolResponseBodyHTTP(BaseModel):
    blueprint: ResponseBodyBlueprint
    r"""The blueprint for the HTTP request. The `arguments` field will be used to replace the placeholders in the `url`, `headers`, `body`, and `arguments` fields."""

    arguments: Optional[Dict[str, ResponseBodyArguments]] = None
    r"""The arguments to send with the request. The keys will be used to replace the placeholders in the `blueprint` field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["arguments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseBodyHTTPToolTypedDict(TypedDict):
    r"""Executes HTTP requests to interact with external APIs and web services using customizable blueprints."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    project_id: str
    workspace_id: str
    created: str
    updated: str
    type: CreateToolResponseBodyToolsResponseType
    http: CreateToolResponseBodyHTTPTypedDict
    id: NotRequired[str]
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    created_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that created the tool"""
    updated_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that last updated the tool"""
    status: NotRequired[CreateToolResponseBodyToolsStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class ResponseBodyHTTPTool(BaseModel):
    r"""Executes HTTP requests to interact with external APIs and web services using customizable blueprints."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    project_id: str

    workspace_id: str

    created: str

    updated: str

    type: CreateToolResponseBodyToolsResponseType

    http: CreateToolResponseBodyHTTP

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = (
        "tool_01M1D09ENE3GQT33N4675C2TDA"
    )

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    created_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that created the tool"""

    updated_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that last updated the tool"""

    status: Optional[CreateToolResponseBodyToolsStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_id", "display_name", "created_by_id", "updated_by_id", "status"]
        )
        nullable_fields = set(["created_by_id", "updated_by_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


CreateToolResponseBodyStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolResponseBodyToolsType = Literal["json_schema",]


class ResponseBodySchemaTypedDict(TypedDict):
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: str
    r"""The JSON Schema type"""
    properties: Dict[str, Any]
    r"""The properties of the JSON Schema object"""
    required: List[str]
    r"""Array of required property names"""


class ResponseBodySchema(BaseModel):
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: str
    r"""The JSON Schema type"""

    properties: Dict[str, Any]
    r"""The properties of the JSON Schema object"""

    required: List[str]
    r"""Array of required property names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class ResponseBodyJSONSchemaTypedDict(TypedDict):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    description: str
    r"""A description of what the response format is for. This will be shown to the user."""
    schema_: ResponseBodySchemaTypedDict
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""
    strict: NotRequired[bool]
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. Only compatible with `OpenAI` models."""


class ResponseBodyJSONSchema(BaseModel):
    name: str
    r"""The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""

    description: str
    r"""A description of what the response format is for. This will be shown to the user."""

    schema_: Annotated[ResponseBodySchema, pydantic.Field(alias="schema")]
    r"""The schema for the response format, described as a JSON Schema object. See the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    strict: Optional[bool] = None
    r"""Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. Only compatible with `OpenAI` models."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["strict"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseBodyJSONSchemaToolTypedDict(TypedDict):
    r"""A tool that enforces structured output format using JSON Schema for consistent response formatting."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    project_id: str
    workspace_id: str
    created: str
    updated: str
    type: CreateToolResponseBodyToolsType
    json_schema: ResponseBodyJSONSchemaTypedDict
    id: NotRequired[str]
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    created_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that created the tool"""
    updated_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that last updated the tool"""
    status: NotRequired[CreateToolResponseBodyStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class ResponseBodyJSONSchemaTool(BaseModel):
    r"""A tool that enforces structured output format using JSON Schema for consistent response formatting."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    project_id: str

    workspace_id: str

    created: str

    updated: str

    type: CreateToolResponseBodyToolsType

    json_schema: ResponseBodyJSONSchema

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = (
        "tool_01M1D09END768AQFDSRTQY5K74"
    )

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    created_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that created the tool"""

    updated_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that last updated the tool"""

    status: Optional[CreateToolResponseBodyStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_id", "display_name", "created_by_id", "updated_by_id", "status"]
        )
        nullable_fields = set(["created_by_id", "updated_by_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ResponseBodyStatus = Literal[
    "live",
    "draft",
    "pending",
    "published",
]
r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


CreateToolResponseBodyType = Literal["function",]


CreateToolResponseBodyToolsResponse200ApplicationJSON1Type = Literal["object",]
r"""The type must be \"object\" """


class ResponseBodyParametersTypedDict(TypedDict):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    type: CreateToolResponseBodyToolsResponse200ApplicationJSON1Type
    r"""The type must be \"object\" """
    properties: Dict[str, Any]
    r"""The properties of the function parameters"""
    required: List[str]
    r"""Array of required parameter names"""


class ResponseBodyParameters(BaseModel):
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: CreateToolResponseBodyToolsResponse200ApplicationJSON1Type
    r"""The type must be \"object\" """

    properties: Dict[str, Any]
    r"""The properties of the function parameters"""

    required: List[str]
    r"""Array of required parameter names"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class CreateToolResponseBodyFunctionTypedDict(TypedDict):
    name: str
    r"""The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    description: NotRequired[str]
    r"""A description of what the function does, used by the model to choose when and how to call the function."""
    strict: NotRequired[bool]
    r"""Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Currently only compatible with `OpenAI` models."""
    parameters: NotRequired[ResponseBodyParametersTypedDict]
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""


class CreateToolResponseBodyFunction(BaseModel):
    name: str
    r"""The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""

    description: Optional[str] = None
    r"""A description of what the function does, used by the model to choose when and how to call the function."""

    strict: Optional[bool] = None
    r"""Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Currently only compatible with `OpenAI` models."""

    parameters: Optional[ResponseBodyParameters] = None
    r"""The parameters the functions accepts, described as a JSON Schema object. See the `OpenAI` [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "strict", "parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseBodyFunctionToolTypedDict(TypedDict):
    r"""A custom function tool that allows the model to call predefined functions with structured parameters."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """
    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""
    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""
    project_id: str
    workspace_id: str
    created: str
    updated: str
    type: CreateToolResponseBodyType
    function: CreateToolResponseBodyFunctionTypedDict
    id: NotRequired[str]
    display_name: NotRequired[str]
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""
    created_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that created the tool"""
    updated_by_id: NotRequired[Nullable[str]]
    r"""The id of the user that last updated the tool"""
    status: NotRequired[ResponseBodyStatus]
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""


class ResponseBodyFunctionTool(BaseModel):
    r"""A custom function tool that allows the model to call predefined functions with structured parameters."""

    path: str
    r"""Entity storage path.

    With workspace-level API keys, use the format `project/folder/subfolder/...`. The first element must be the display name of an existing project, followed by nested folders (auto-created as needed). Example: `Default Project/agents`.

    With project-level API keys, the project is predetermined by the API key, so the path is relative to that project. Example: `agents`. For backward compatibility, a leading project name is ignored when it matches the scoped project.
    """

    key: str
    r"""Unique key of the tool as it will be displayed in the UI"""

    description: str
    r"""A description of the tool, used by the model to choose when and how to call the tool. We do recommend using the `description` field as accurate as possible to give enough context to the model to make the right decision."""

    project_id: str

    workspace_id: str

    created: str

    updated: str

    type: CreateToolResponseBodyType

    function: CreateToolResponseBodyFunction

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = (
        "tool_01M1D09ENC4C6R3E959QKS214K"
    )

    display_name: Optional[str] = None
    r"""The name of the tool as it will be displayed in the UI. This is optional and if not provided, the `key` will be used."""

    created_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that created the tool"""

    updated_by_id: OptionalNullable[str] = UNSET
    r"""The id of the user that last updated the tool"""

    status: Optional[ResponseBodyStatus] = "live"
    r"""The status of the tool. `Live` is the latest version of the tool. `Draft` is a version that is not yet published. `Pending` is a version that is pending approval. `Published` is a version that was live and has been replaced by a new version."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_id", "display_name", "created_by_id", "updated_by_id", "status"]
        )
        nullable_fields = set(["created_by_id", "updated_by_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


CreateToolResponseBodyTypedDict = TypeAliasType(
    "CreateToolResponseBodyTypedDict",
    Union[
        ResponseBodyFunctionToolTypedDict,
        ResponseBodyJSONSchemaToolTypedDict,
        ResponseBodyHTTPToolTypedDict,
        ResponseBodyCodeExecutionToolTypedDict,
    ],
)
r"""Successfully created the tool."""


CreateToolResponseBody = Annotated[
    Union[
        Annotated[ResponseBodyFunctionTool, Tag("function")],
        Annotated[ResponseBodyJSONSchemaTool, Tag("json_schema")],
        Annotated[ResponseBodyHTTPTool, Tag("http")],
        Annotated[ResponseBodyCodeExecutionTool, Tag("code")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""Successfully created the tool."""


try:
    RequestBodyJSONSchema.model_rebuild()
except NameError:
    pass
try:
    ResponseBodyCodeExecutionTool.model_rebuild()
except NameError:
    pass
try:
    ResponseBodyHTTPTool.model_rebuild()
except NameError:
    pass
try:
    ResponseBodyJSONSchema.model_rebuild()
except NameError:
    pass
try:
    ResponseBodyJSONSchemaTool.model_rebuild()
except NameError:
    pass
try:
    ResponseBodyFunctionTool.model_rebuild()
except NameError:
    pass
