"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileContentPartSchemaTypedDict(TypedDict):
    r"""File data for the content part. Must contain exactly one of file_data, file_id or uri."""

    file_data: NotRequired[str]
    r"""The file data as a data URI string in the format 'data:<mime-type>;base64,<base64-encoded-data>'. Example: 'data:image/png;base64,iVBORw0KGgoAAAANS...'"""
    uri: NotRequired[str]
    r"""URL of the file. Supported for PDFs on Anthropic Claude models and for `https://` and Google Cloud Storage `gs://` URIs on Vertex AI Gemini models."""
    mime_type: NotRequired[str]
    r"""MIME type of the file (e.g., application/pdf, image/png). Inferred from `filename` or the URI extension when omitted."""
    file_id: NotRequired[str]
    r"""A provider file reference: a Google Cloud Storage `gs://` URI for Vertex AI Gemini models, or an OpenAI file ID (`file-...`) for OpenAI models."""
    filename: NotRequired[str]
    r"""The name of the file, used when passing the file to the model as a string."""


class FileContentPartSchema(BaseModel):
    r"""File data for the content part. Must contain exactly one of file_data, file_id or uri."""

    file_data: Optional[str] = None
    r"""The file data as a data URI string in the format 'data:<mime-type>;base64,<base64-encoded-data>'. Example: 'data:image/png;base64,iVBORw0KGgoAAAANS...'"""

    uri: Optional[str] = None
    r"""URL of the file. Supported for PDFs on Anthropic Claude models and for `https://` and Google Cloud Storage `gs://` URIs on Vertex AI Gemini models."""

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None
    r"""MIME type of the file (e.g., application/pdf, image/png). Inferred from `filename` or the URI extension when omitted."""

    file_id: Optional[str] = None
    r"""A provider file reference: a Google Cloud Storage `gs://` URI for Vertex AI Gemini models, or an OpenAI file ID (`file-...`) for OpenAI models."""

    filename: Optional[str] = None
    r"""The name of the file, used when passing the file to the model as a string."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_data", "uri", "mimeType", "file_id", "filename"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FileContentPartSchema.model_rebuild()
except NameError:
    pass
