"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProjectBudgetScopeRestResponseTypedDict(TypedDict):
    r"""Per-project cap."""

    project_id: NotRequired[str]


class ProjectBudgetScopeRestResponse(BaseModel):
    r"""Per-project cap."""

    project_id: Annotated[Optional[str], pydantic.Field(alias="projectId")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["projectId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ProjectBudgetScopeRestResponse.model_rebuild()
except NameError:
    pass
