"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_ai_sdk.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, Literal
from typing_extensions import TypedDict


ResponseFileSearchCallSearchingStreamEventType = Literal[
    "response.file_search_call.searching",
]
r"""The event type. Discriminates the payload."""


class ResponseFileSearchCallSearchingStreamEventTypedDict(TypedDict):
    r"""A `response.file_search_call.searching` server-sent event."""

    item_id: str
    r"""ID of the output item this event refers to."""
    output_index: int
    r"""Index of the output item in the response output array."""
    sequence_number: int
    r"""Monotonically increasing sequence number for ordering events."""
    type: ResponseFileSearchCallSearchingStreamEventType
    r"""The event type. Discriminates the payload."""


class ResponseFileSearchCallSearchingStreamEvent(BaseModel):
    r"""A `response.file_search_call.searching` server-sent event."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    item_id: str
    r"""ID of the output item this event refers to."""

    output_index: int
    r"""Index of the output item in the response output array."""

    sequence_number: int
    r"""Monotonically increasing sequence number for ordering events."""

    type: ResponseFileSearchCallSearchingStreamEventType
    r"""The event type. Discriminates the payload."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
